//
//  CaylarViewController.swift
//  BirTutamSaglik
//
//  Created by GAMZE AKYÜZ on 14.04.2022.
//


import UIKit

class CaylarViewController: UIViewController ,UITableViewDelegate,UITableViewDataSource{

    var caylar = [Caylar]()
    var caySec : Caylar?

    @IBOutlet weak var tableView: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()
        cayEkle()
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return caylar.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.text = caylar[indexPath.row].adi
        return cell
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        caySec = caylar[indexPath.row]
        self.performSegue(withIdentifier: "toCaylarDetayViewController", sender: nil)
    }
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "toCaylarDetayViewController"{
            let destinationVC = segue.destination as! CaylarDetayViewController
            destinationVC.selectedCaylar = caySec
        }
    }
    
    func cayEkle(){

        let adacayi = Caylar(Adi: "Adaçayı", Resim: UIImage(named: "adacayiCayi")!, Faydalari: "Depresyonu ve stresi azaltır.Zararlı toksinlerin vücuttan atılmasına yardımcı olur.Beyin fonksiyonlarını geliştirir.Ağız ve diş eti hastalıklarına iyi  gelir.Cilt leke ve hastalıklarında kullanır.Mide ve kolestrol hastaları için rahatlatıcı etkisi vardır.Menopoz sonrası belirtileri hafifletir.Sindirim sistemini korur ve ishale iyi gelir.Aşırı terlemeyi azaltır.", Yapilisi: "Ada çayı genellikle kaynatılarak yapılsa da aslında demlenerek hazırlanması gerekir. Bu sayede besin değerleri daha iyi korunur ve daha yoğun ada çayı tadı elde edilebilir. Kaynar suda çok uzun süre tutulması hem bitkinin faydalı etkilerini kaybetmesine neden olur hem de çayın tadı acılaşabilir. Ada çayının 2 dakikadan uzun süre kaynatılması ile toksik bileşenler açığa çıkarak çayın zararlı hale gelebileceği öne sürülmektedir. Yaklaşık 2 gram ada çayı üzerine 200-250 ml kaynar su ilave edilerek 10 dakika kadar demlenir. Yaprakları süzülür ve fincana doldurularak servis edilir.")
        caylar.append(adacayi)
        
        let ahududu = Caylar(Adi: "Ahududu", Resim: UIImage(named: "ahududuCayi")!, Faydalari: "Ahududunun içerisinde yüksek miktarda C vitamini bulunuyor. Aynı zamanda değerli bir antioksidan kaynağı olan ahududu düzenli olarak tüketildiği takdirde bağışıklık sistemini güçlendirerek hastalıklara karşı verilen mücadelede vücudun sağlam kalmasına olanak tanır.Ödem atıcı özellik göstererek vücuttaki şişkinliğin atılmasına yardımcı olur.Kas güçlendirici özelliğiyle rahim kaslarını güçlendirerek hamileliğin son aylarında meydana gelmesi muhtemel düşük riskini azaltır, doğumun yaklaşmasıyla ortaya çıkan ağrıların şiddetini dindirir.Yapısında yüksek oranda bulunan bitkisel kimyasallar antimikrobiyal etkiler göstererek zararlı bakterilerin vücuttan uzaklaştırılmasına olanak sağlar.İçeriğinde meyve asitleri sayesinde dişlerde ki plak oluşumu önlenir, düzenli olarak tüketildiği takdirde diş kayıplarının büyük bir ölçüde önüne geçer.Tümör gelişimini engellediği kanıtlanmıştır. Fenol ve flavonoid bileşikleri açısından zengindir. Özellikle kırmızı ahududu bazı kanser türlerinde kanserli hücrelerin vücudun farklı bölgelerine yayılmalarına engel olur.", Yapilisi: "Önce ahududunun yapraklarını bir örtünün üzerinde kurutun. Kurutma işlemini yaptığınız alan sıcak ancak güneş ışığını direkt olarak almayan bir yer olsun. Yapraklar kuruduktan sonra cam kavanozda bir sene boyunca muhafaza edilebilir. Bu kurumuş yapraklardan çay hazırlamak için aşağıdaki adımları takip edin.Bir litrelik kaynamış suyun içerisinde 50 gram ahududu ilave edin. 10 dakika boyunca kaynadıktan sonra içime hazır hale gelecektir. Bu çayı dilerseniz sıcak dilerseniz de ılık bir şekilde günde üç bardağı geçmeyecek şekilde tüketebilirsiniz. Eğer çay gargara yapak için kullanılacak su miktarı azaltılabilir. Ya da bunun yerine karışımın içerisine atılan kurutulmuş ahududu yaprağı miktarı artırılabilir.")
        caylar.append(ahududu)
        
        let anason = Caylar(Adi: "Anason Çayı", Resim:UIImage(named: "anasonCayi")!, Faydalari: "Solunum sistemini temizler. Bronşit, astım ve soğuk algınlığı gibi rahatsızlıklarda yardımcı olur.Anason çayı yemeklerden sonra ve uyumadan önce içildiği zaman uyku bozukluklarına iyi gelir.Sindirim sistemini rahatlatır.Mide ülserini tedavi eder.Zihinsel yorgunlukları giderir.Migren ağrılarının şiddetini dindirir.Anne sütünü artırıcı etki gösterir.Öksürüğü keser, balgamı söktürür.İştahsızlık problemlerini giderir.Kan dolaşımını düzenler.Anason daha çok ağrı kesici özelliği ile bilinmektedir.Anason çayı doktor gözetiminde kullanılması ile bebeklerde gaz problemlerini giderir.Sedef, uyuz vb. cilt hastalıklarına iyi gelmektedir.İshal, kusma vb. rahatsızlıklara iyi gelir.Arka arkaya gelen ve geçmeyen hıçkırıkları dindirmede fayda sağlar.", Yapilisi: "Bir çay kaşığı kurutulmuş anason yaprağı ile bir bardak anason çayı elde edilir. Kaynamış suya anason yaprağı eklenilir ve kaynatılır. 7-10 dakika kadar demlendirilir. Çayın tadını alabilmesi için iyice demlenmesi gerekmektedir.")
        caylar.append(anason)
        
        let ananas = Caylar(Adi: "Ananas Çayı", Resim: UIImage(named: "ananasCayi")!, Faydalari: "nanasın içeriğindeki zengin C vitamini ve B vitamini sayesinde cilde sağlıklı bir görünüm kazandırır.B Vitaminin etkisiyle cilde istediği nemi hapseder.Kadınlarda doğurganlığı arttırır.Kemik yapısını kuvvetlendirir.Nezle ve solunum yollarındaki rahatsızlıklarda iyileşme sürecini hızlandırır.Göz rahatsızlıklarına iyi gelmekle beraber görme sorunu yaşayan insanların sorunlarına engel olur.Kanser riskini azaltır.Ağız ve diş sağlığını kuvvetlendirir.Stresi yok eder.Ödem ve şişkinlik sorunu yaşayan kişilerde ödemin kolayca atılmasına sebep olur.Vücudu toksinlerden arındırır.", Yapilisi:"Ananas çayı yapımı için ananasın kabukları güzelce soyulur. Soyulan kabuklar yaklaşık olarak 1 saat tuzlu suyun içinde bekletilir. Bu işlem sonrasında kabuklar tuzlu sudan arındırılarak yaklaşık olarak 1 litre suyun içine atılır. Ananas çayı tarifi olarak çeşitlendirdiğimizde kişilerin damak zevkine göre içerisine taze zencefil, limon ve tarçın gibi tatlandırıcı ve yararlı besinler atılabilir. Tüm malzemeler eklendikten sonra kısık ateşte kaynamaya bırakılır. Kaynadıktan sonra dilediğiniz vakitte sıcak veya soğuk olarak tüketebilirsiniz.")
        caylar.append(ananas)
        
        let alic = Caylar(Adi: "Alıç", Resim: UIImage(named: "alicCayi")!, Faydalari: "Depresyonu önler. Strese iyi gelir.Ruhsal sorunlara iyi gelir.Sinir hücrelerini yatıştırır.Kaygı ve endişeyi azaltır.Bağışıklık sistemini düzenler.Sindirimi güçlendirir.Vücuttaki radikalleri temizler.Hastalıklara karşı korur.Güçlü antioksidan özelliği vardır.C vitamini bakımından zengindir.Soğuk algınlığı hastalıklarına karşı faydalıdır.İshale iyi gelir.Potasyum kaynağıdır.Kalp ve damar tıkanıklığına iyi gelir.Tükürükte yer alan enfeksiyonları temizler.Ağız kokusunu önler.", Yapilisi: "Bir bardağa kaynar su doldurulur ve 1 çay kaşığı kurutulmuş alıç meyvesi kaynar suya eklenir.Hazırlanan karışım 8-10 dakika kadar demlenir.Hazır olan çay süzgeçten geçirilir. Tatlandırmak için isteğe göre bal ya da şeker eklenebilir.Alıç çayı soğutularak 3 gün boyunca buzdolabında muhafaza edilebilir")
        caylar.append(alic)
        
        let arpa = Caylar(Adi: "Arpa", Resim: UIImage(named: "arpaCayi")!, Faydalari: "Diş sağlığı üzerine olumlu etkileri vardır. Mide bulantısına iyi gelir.Kalp sağlığını korumaya yardımcıdır.Lif, magnezyum ve B vitaminleri (B 12 hariç) açısından zengin içeriğe sahip arpanın çözünmez lif içeriği yüksek olduğundan kolesterol düşürücü etkisi var.Arpa çayı doğru ve kontrollü kullanılırsa kalp-damar hastalıklarına ve koroner kalp rahatsızlıklarına olumlu etki sağlar.Vücudu toksinlerden temizleyen arpa çayı, böbrek, karaciğer ve akciğer dostu.Kan şekerini dengelemeye yardımcı olur.Alkali bir yapıda olmasıyla sindirimi ve hazmı kolaylaştırır.İyi bir antioksidan içeriğe sahip olmasıyla yaşlılık etkilerine karşı savaşçıdır.", Yapilisi: "Tavaya koyulan arpalar renkleri koyu kahverengi olana kadar kavrulur.Kavrulmuş arpalar karabiber öğütücü yardımı ile ince toz haline getirilir. Karabiber öğütücünün mevcut olmaması halinde, arpa havanda dövülerek de aynı işlem gerçekleştirilebilir.1 litre suyu kaynatılır.Kaynamış suya 3-4 kaşık arpa eklenir.Arpanın kaynar suda 4 dakika demlenmesi beklenir. Demlenen arpalar 15 dakika oda sıcaklığında soğumaya bırakılır ve ardından içime hazır hale gelir.")
        caylar.append(arpa)

        let biberiye = Caylar(Adi: "Biberiye", Resim: UIImage(named: "biberiyeCayi")!, Faydalari: "Biberiye çayı, yapıldığı biberiye bitkisinden aldığı güç sayesinde tam bir vitamin ve mineral deposu desek yeri. İçinde B1, B6, B12 gibi B grubu vitaminleri başta olmak üzere, C, D, E ve K vitaminleri bulunuyor. Bunun yanında demir, kalsiyum ve fosfor mineralleri bakımından da en zengin içecekler arasında yer alıyor.Biberiye çayının en etkili olduğu konulardan biri hafıza. Kendisi hafızayı güçlendirmekle kalmıyor, aynı zamanda konsantrasyonun da artmasına yardımcı oluyor. Üstelik bu özelliğini sadece kokusuyla bile hissettirebiliyor.Beynin sağlıkla çalışmasına destek olduğundan baş ağrılarına da iyi geldiği biliniyor. Bu etkisinden faydalanmak için demlenen biberiye çayının buharının solunması tavsiye ediliyor.Buhar banyosu da denilen bu yöntem uygulandığında biberiye çayı solunum yolları sorunlarına da çözüm oluyor, burun tıkanıklıklarının hızla geçmesini sağlıyor.İçeriğindeki C vitamini sayesinde güçlü antioksidan özellikler gösteren biberiye çayı, vücudu hastalıklardan koruma konusunda da oldukça etkili oluyor. Düzenli kullanımında bağışıklık sistemini güçlendirici özellikler gösterdiği biliniyor.Antiseptik özellikler gösterdiğinden ağız içinde, boğazda oluşan yaraların, tahrişlerin de hızla geçmesini sağlıyor.Sindirim sisteminin de sağlıklı bir şekilde çalışmasına destek olan bu çay, hazımsızlık, mide ağrısı gibi sorunların da önüne geçiyor.Aynı şekilde boşaltım sistemini ve bağırsak hareketleri de olumlu yönde etkileyen biberiye çayı, kabızlık sorunu yaşayanlara sıklıkla öneriliyor.Antioksidan etkisi sayesinde ödem attırıcı ve idrar söktürücü özellikler gösterdiği de biliniyor.Yine antioksidan etkisi sayesinde kan dolaşımını hızlandırıyor, bu da kış günlerinde içinizin daha sıcak olmasını sağlıyor.Faydalı, düşük kalorili ve sindirin-boşaltım sistemlerini olumlu yönde etkileyen bir içecek olduğundan zayıflamaya da yardımcı oluyor.", Yapilisi: "Küçük bir cezvenin içerisine su konularak kaynatılır. Sonrasında ise bu suyun içerisine bir miktar toz ve ya taze biberiye eklenir. Bu karışım birlikte 5 dakika daha kaynatıldıktan sonra demlenmeye bırakılır. Biberiye tüm aromasını suya bıraktıktan sonra biraz ılıması beklenerek çay süzülür. fincana alınan biberiye çayına bal eklenerek tüketilir. ")
        caylar.append(biberiye)


        let bogurtlen = Caylar(Adi: "Böğürtlen", Resim: UIImage(named: "bogurtlenCayi")!, Faydalari: "Göz sağlığı için oldukça faydalı etkileri vardır.Düzenli olarak tüketimi halinde vücutta bulunan zararlı serbest radikallerin vücut dışına atılmasına yardım eder.Bağışıklık sisteminin güçlendirir.Kış aylarında grip, nezle gibi solunum yolu hastalıklarına karşı etkin bir koruma sağlar.Zengin C vitamini içeriği ile kemik dokularını kuvvetlendirir.Ağız yaralarını iyileştirir, nefesi tazeler ve ağız içinde bakteri oluşumunu engeller.Kan şekerini dengeleyici özellik taşır.Cildi güzelleştirir. Cildi sıkılaştırarak faydalı olur.İdrar yollarında oluşan enfeksiyonların tedavisine yardımcı olur.Tansiyonu dengeler. Kötü kolesterolün düşürülmesine yardım eder.Vücudun yağ dengesini koruyucu bir etkiye haizdir.Mesanede taş oluşmasına engel olur.İçeriğinde bulunan K vitamini ile kanın pıhtılaşmasına yardımcı olarak yaralar üzerinde olumlu etkiler sağlar.", Yapilisi: "Böğürtlen çayını hazırlarken ilk önce kurutulan böğürtlen yaprakları bir demliğe konulur. Sonra bu yaprakların üzerine kaynamış su eklenerek 10 dakika kadar demlenmeye bırakılır. 10 dakika dolduktan sonra süzülerek afiyetle tüketime hazır hale gelir. Günde iki fincan böğürtlen çayı tüketimi tavsiye edilmektedir.")
        caylar.append(bogurtlen)
        
        let civanpercemi = Caylar(Adi: "Civanperçemi", Resim: UIImage(named: "civanpercemi")!, Faydalari: "Civanperçemi çayının sağlığa olan faydaları saymakla bitmez. Bunlardan ilki ve en önemlisi ise kadınlara olan faydasıdır. Kadınlarda sıkça karşılaşılan beyaz akıntıyı keser. Ayrıca genital bölge ve yumurtalık enfeksiyonlarına, rahim kanserini önlemeye yardımcı olmaktadır.Mide rahatsızlıklarını gidermeye yardımcı olur.İştah açıcı özelliği vardır.Midede oluşan gazı gidermeyi sağlar.Bağırsakları çalıştırır, kabızlığa karşı etkilidir.Civanperçemi çayı soğuk kış aylarında, grip, nezle ve öksürüğe karşı etkili olmaktadır.Ateş düşürücü ve balgam söktürücüdür.Migren ağrılarını giderir.Kalp ve damar hastalıklarına iyi gelmektedir.Baş dönmesi ve yüksek tansiyon için faydalı bir besin ürünüdür.Cilt sağlığını korur ve cilde güzellik verir.Sivilce ve akne tedavisinde kullanılmaktadır.Stres, kaygı ve uykusuzluk problemlerine iyi gelmektedir.", Yapilisi: "Civanperçemi çayı hazırlarken ilk önce, 3 veya 4 adet kadar civanperçemi 1 su bardağı kadar kaynar suyun içerisine atınız.Daha sonra en az 10 dakika demlenmesi bekleyin.Demlendikten sonra süzüp gönül rahatlığı ile tüketebilirsiniz.Civanperçemi çayı kaç gün içilmeli diye soracak olursanız, günde 2 bardak içmeniz yeterli olmaktadır. Aşırı tüketmemeye özen gösteriniz. Aksi takdirde hassas bünyesi olan kişilerde alerjik reaksiyonlara neden olabilir. Ayrıca kalp ritmini bozabilir ve kabızlık sorununa sebep olabilmektedir.")
        caylar.append(civanpercemi)
        
        let cuhacicegi = Caylar(Adi: "Çuha Çiçeği", Resim: UIImage(named: "cuhacicegi")!, Faydalari: "Baş ağrılarınızı gidermek için etkili bir bitki çayıdır.Bağırsak probleminiz varsa, kabızlık şikayetlerinizden kurtulamadıysanız çuha çiçeği çayı oldukça faydalı olacaktır.Antioksidan özelliği sayesinde, sık sık idrara çıkmanızı sağlar. Böylece vücudunuzda biriken ödemi kolayca atabilirsiniz.Solunum yolunuzu rahatlatarak daha iyi nefes almanızı sağlar.Kalp sağlığını korumak için ideal bir sıcak içecektir.Stres, kaygı ve yorgunluğu üzerinizde almaya yardımcı olur.Saç dökülmesini önleyici özelliği de bulunmaktadır.Diyabet hastaları için kan şekerini dengeleyen bir yapıya sahiptir.Kadın ve erkeklerde doğurganlığı sağlar.Regl döneminde oluşan sancıları yok ederek daha iyi hissetmenizi sağlar.", Yapilisi: "Eğer kuru yapraklardan çay demleyecekseniz, bir çay kaşığı kuru çuha çiçeğini 1 bardak sıcak su içine ekleyin. 10 dakika kadar demlendikten sonra yaprakları süzüp çayı içebilirsiniz.Çuha çiçeğinin kökünden çay demlemek istediğinizde ise kökten elde edilen parçalar işe yarayacaktır. 1 bardak sıcak suyun içine 1 tatlı kaşığı kök parçalarını ilave edin. 10 dakika kadar bekledikten sonra kökleri çıkarıp çayınızı içebilirsiniz.Düzenli olarak kullandığınız ilaçlar varsa çuha çiçeği yağı yan etkileri görülebilir. Bu nedenle ilaç kullanan kişilerin doktordan onay alarak çuha çiçeği çayı içmesi tavsiye edilir.")
        caylar.append(cuhacicegi)
        
        let defneyapragi = Caylar(Adi: "Defne Yaprağı", Resim: UIImage(named: "defneyapragi")!, Faydalari: "Defne yaprağının çayı oldukça faydalıdır. İçeriğinde A vitamini bulunduran defne yaprağı aynı zamanda yüksek oranda manganez, kalsiyum ve magnezyum içeriyor. Defne yaprağı çayı vücuttaki yoğun terlemeyi azaltır. Bunun yanı sıra göz sağlığını korur ve şişkinliği de azaltır. Yüksek oranda antioksidan içeren defne yaprağı çayı cilde çok iyi gelmektedir. Defne yaprağı çayı iştah açmasının yanı sıra uykuyu da düzenler. Öksürüğe iyi gelen defne yaprağı balgam da söktürmektedir. Ayrıca defne yaprağı çayı tüm hastalıklara karşı vücudu da güçlendirir. Yağlı ciltlerde ise yaraların hızlı iyileşmesini sağlar.", Yapilisi: "En faydalı bitkiler arasında yer alan defne yaprağını çayı da doğru usullerde demlenmelidir. Özellikle de defne yaprağı çayı iki farklı şekilde hazırlanabilir. Özellikle su iyice kaynatılmalıdır. Hemen ardından ise 3 adet defne yaprağı da bu suya konulur. yaklaşık 4 dakika kadar çay demlenir. Bunun ardından ise çay süzülerek 8 dakika beklenir. Bu çayın tadı sert olur ise 3 yemek kaşığı süt ve ya bal ile tatlandırılır. Aynı zamanda defne yaprağı çayı bir de başka türlü hazırlanabilir. Özellikle de su ile defne yaprağı birlikte kaynatılıp 4 dakika kaynatıldıktan sonra süzülür.")
        caylar.append(defneyapragi)
        
        let ebegumeci = Caylar(Adi: "Ebegümeci", Resim: UIImage(named: "ebegumeciCayi")!, Faydalari: "Öksürük ve bronşit gibi sağlık sorunlarını gidermeye yardımcı olur.Ebegümeci çayı ayrıca ayak şişkinlerinde, kırık ve çıkıklardan dolayı oluşan şişkinliklerin giderilmesi için, şiş olan yere masaj yaparak sürerseniz kısa süre içerisinde şişkinliğin indiğini göreceksiniz.-Göz sağlığını korumaya yardımcı olmaktadır.-Soğuk kış aylarında alınan soğuk algınlığı, nezle ve grip gibi hastalıklara iyi gelmektedir.Ateş düşürmeye yardımcı olmaktadır.Burun tıkanıklığı sorununu giderir,Mide ağrısına ve mide bulantısı gibi sorunları gidermektedir.Bağırsakların düzenli çalışmasını sağlamaktadır.Cildinizi korur.Gözaltı kırışıklarına iyi gelmektedir. Ebegümeci çayını masaj yaparak gözaltınıza sürebilirsiniz.Kabızlık sorunu giderirDişlerini korur, dişeti rahatsızlıklarına iyi gelir", Yapilisi: "Ebegümeci çayı hazırlamak için ilk önce 1 litre suyu boş bir tencereye ilave ediniz.Daha sonra 2 tatlı kaşığı kurutulmuş ebegümeci çiçeğini kaynar suya ekleyiniz.Kaynamaya bıraktığınız suyu 5 dakika boyunca demlemesini bekleyin.Demledikten sonra, süzüp tüketebilirsiniz.Günde 2 fincan ebegümeci çayını tüketebilirsiniz. Hem lezzetli bir içecek hem de düzenli bir şekilde tüketimi sonucu kilo verebilirsiniz.")
        caylar.append(ebegumeci)
        
        let elma = Caylar(Adi: "Elma", Resim: UIImage(named: "elmaCayi")!, Faydalari: "Antioksidan açısından zengin olan elma çayı bağışıklık sistemini güçlendirerek vücudu hastalıklara karşı korur.Yüksek oranda A, C, E ve D vitamini içeren elma çayı toksin maddelerin vücuttan atılmasını sağlayarak başta göz sağlığı, dolaşım sistemi ve boşaltım sistemi üzerinde olumlu etkiler yaratır.Ferahlatıcı etkiye sahip olan elma çayı vücudun daha canlı olmasını sağlar ve içeriğindeki özel bileşenler başta baş ağrısı olmak üzere vücut ağrılarının dindirilmesinde faydalıdır.Özellikle tarçın ile birlikte tüketildiğinde içeriğinde yer alan manganezin etkisi ile kolesterolün düzenlenmesinde etkin bir rol oynar. Ayrıca tarçın ile birlikte kan şekerini düzenleyici etkisi de elma çayı faydaları arasındadır.İçeriğinde yer alan B6 vitamini sayesinde oksijenin kanda taşınmasını destekleyen elma çayı, beyaz kan hücresi yapımında önemli rol oynayan lenfleri korur.", Yapilisi: "Taze elma çayı demlemek için öncelikle elmaları bol su ile güzelce yıkayın.Daha sonra yıkadığınız elmaların kabuklarını soyun.Kabukları soyulan elmanın çekirdeklerini çıkartarak ince ince dilimleyin.Hem elma kabuklarını hem de dilimlediğiniz elmaları 2 su bardağı su ile demliğe koyun.Demliği orta ateşte kaynatarak altını kapatın ve 10 dakika demlemeye bırakın.Çayınız ılıyınca süzerek tüketimini gerçekleştirin.İçiminize lezzet katmak için karanfil karanfil ya da tarçın da ekleyebilirsiniz.")
        caylar.append(elma)
        
        let enginar = Caylar(Adi: "Enginar", Resim: UIImage(named: "enginarCayi")!, Faydalari: "Enginar çayı sindirim sisteminin gelişmesinin ve düzenli bir şekilde çalışmasını sağlamaktadır.İçerisinde bulunan lifler sayesinde bağırsak hareketlerini düzenlemeye yardımcı olur ve daha rahat kilo vermeyi sağlamaktadır.İdrar söktürücü etkisi vardır.Mesane problemlerini gidermeye yardımcı olur.Kötü kolesterol seviyesini düşürür ve ayrıca kolesterolü dengeler.Kalp hastalıkları oluşumunu engeller.Antioksidan özelliği ile vücudu çeşitli hastalıklara karşı korumaya yardımcı olur.Cilt sağlığını korumaya yardımcı olur ve ayrıca deride mantar oluşumunu önlemektedir. Ayrıca enginar Çayının sivilceye faydası da bulunmaktadır. Enginar çayını yüzünüze uyguladığınız zaman, cildinizde bulunan akne ve sivilcenizi yok etmeye yardımcı olur. Düzenli olarak kullandığınızda faydasını görmüş olacaksınız.Enginar çayı saç köklerini güçlendirerek saçların sağlıklı görünmesini sağlar.İçerisinde bulunan K vitamini sayesinde kemikleri güçlendirir ve geliştirmeye yardımcı olur.Enginar çayı, kan basıncını dengeler ve damar tıkanıklığını engeller.", Yapilisi: "Lezzetli bir enginar çayı hazırlarken ilk önce kurutulmuş olan enginar yapraklarını su dolu bir tencereye ilave ediniz.Daha sonra suyun 5 dakika daha kaynatılmasını bekleyiniz.Ağzı kapalı şekilde 10-15 dakika kadar demlendikten sonra afiyetle içebilirsiniz.Günde 1 bardak enginar çayı tüketebilirsiniz.")
        caylar.append(enginar)

        let feslegen = Caylar(Adi: "Fesleğen", Resim: UIImage(named: "feslegenCayi")!, Faydalari: "Fesleğen bitkisinin en az kendisi kadar çayının da faydaları oldukça fazla bulunmaktadır. Bunlardan ilki antiseptik, sedatif ve diüretik etkilere sahiptir Ayrıca fesleğen bitkisinin içeriğinde bulunan antioksidan maddeler vücudun temizlenmesine ve zararlı toksinlerin dışarı atılmasına yardımcı olmaktadır.Diğer bir faydası ise, vücuttaki toksinlerin dışarı atılmasını sağlayan fesleğen çayı daha kısa sürede kilo vermenize yardımcı olmaktadır.Fesleğen çayı bağışıklık sisteminin güçlenmesine yardımcı olmaktadır.Şifa deposu olan fesleğen çayı vücudu enfeksiyonlara karşı korur.Soğuk kış aylarında grip, nezle gibi hastalıklardan korumaya yardımcı olur.Bu çayın, stres azaltıcı ve kortizon dengeleyici etkileri bulunmaktadır.Vücutta bulunan iltihap gibi problemlerin giderilmesine yardımcı olur.Bu çay idrar yolunda üreyen bakterileri yok etmeye yardımcı olur.Fesleğen çayı hem fiziksel hem de zihinsel olarak sizi rahatlatır.Ağız içeriğindeki bakterilerin oluşmasını önler. Ayrıca ağız kokusunu yok eder ve iltihabı azaltmaya yardımcı olmaktadır.Tansiyon ve baş ağrısını gidermeye yardımcı olmaktadır.Fesleğen çayı yaşla birlikte gelen kırışıklık ve lekelerden cildinizi korumaya yardımcı olan mucizevi bir besindir.Ağır yemeklerden sonra oluşan hazımsızlık problemini gidermeye yardımcı olur.Bu çay enflamasyonu düşürür, vücutta biriken fazla sıvıların atılmasını sağlar ve vücudunuzda meydana gelen ağrıya karşı yardım edebilen bir çaydır.Fesleğen çayı ayrıca anne sütünü arttırmaya yardımcı olan harika bir besin ürünüdür.Bağırsaklarda gaz oluşumunu engellemeyi sağlar.", Yapilisi: "Fesleğen çayını hazırlarken ilk önce elma çekirdeği ve fesleğen tohumları bir gün önceden ballı suda dinlendiriniz.Daha sonra bir tutam yonca, 3 adet kuru kayısı ve yarım tutam lavanta çiçeğini Ballı suda 20 dakika kaynatınız.Kaynatılan çayınızı süzüp afiyetle tüketebilirsiniz.Günde 1-2 bardak fesleğen çayını tüketebilirsin. Gereğinden fazla tüketmemeye özen gösteriniz.")
        caylar.append(feslegen)
        
        let ginkgobiloda = Caylar(Adi: "Ginkgo Biloda", Resim: UIImage(named: "ginkgobilodaCayi")!, Faydalari: "Ginkgo biloba, son yıllarda depresif sorunların giderilebilmesi için de kullanılmaktadır. Nitekim ginkgo biloba özü; merkezi sinirleri etkileyebilecek ölçüde bileşenler ve asitler içermektedir. Ginkgo biloba çayı, migren ağrılarına deva olabilmektedir. Ginkgo biloba, E vitamini açısından da oldukça zengindir. Cilt sağlığının korunmasına da destek olur.Ginkgo biloba çayı; Alzheimer hastalığı, hafıza kaybı sorunları ve diğer tüm nöral sorunlara karşı savaşmaktadır.Ginkgo biloba, felç geçirme riskini ciddi ölçüde azaltmaktadır. Kan pıhtısı oluşumunu azaltarak, kişinin felç geçirme riskini düşürür. Aynı zamanda ginkgo biloba çayı, hasarlı beyin hücrelerinin iyileşmesini de sağlamaktadır.Ginkgo biloba çayının, antioksidan özelliği vardır. Vücuttaki hücreleri, serbest radikallerin zararlı tüm etkilerinden korur. Aynı zamanda, hücreleri onarır.Gingkgo biloba çayı, gözlere çok faydalı bir çaydır. Gözlere olan kan akışını arttırdığı ve bunun sonucunda, kornea ve retinaya gelebilecek zararları da önlediği belirtilmektedir.Ginkgo biloba çayı, saç dökülmesini azaltabilmektedir. Erkeklerde sıklıkla rastlanan kellik sorunu için de, faydalı olduğu kanıtlanmıştır.Ginkgo bilobanın, enerji verici bir özelliği vardır. Ginkgo Biloba çayını, sabah ve akşam demleyip günde iki bardak içmek; bünyeyi zinde tutar.", Yapilisi: "Günde iki kez aç ya da tok karına içilebilecek Ginkgo biloba çayını hazırlamak için, önce bir bardak su kaynatılır. Daha sonra, kaynamış suyun içine; bir tutam kadar Ginkgo Biloba yaprağı atılır. Beş dakika kadar, çay demlendirilir. Bu yolla, Ginkgo Biloba çayı yapılır. Ginkgo biloba çayında, demleme süresine dikkat edilmelidir.")
        caylar.append(ginkgobiloda)
        
        let ginseng = Caylar(Adi: "Ginseng", Resim: UIImage(named: "ginsengCayi")!, Faydalari: "İçeriğinde yer alan antioksidan bileşenler sayesinde bağışıklık sistemini güçlendiren ginseng çayı hastalıklara karşı direnci arttırır.Yüksek vitamin ve mineral içeriğine sahip olan ginseng çayı toksin maddelerin ve vücutta biriken ödemin atımını kolaylaştırır.Ginseng çayının antioksidan özelliği DNA hasarına neden olan serbest radikallerin vücuttan atılmasına yardımcı olur.Kan basıncının düzenlenmesinde önemli bir rol oynar. Ancak yüksek tansiyon hastalarının doktora danışarak kullanması gereklidir.Özellikle tip 2 diyabet hastalarının kan şekerinin düzenlenmesinde etkilidir.Konsantrasyonu arttıran ginseng çayı aynı zamanda hafızanın güçlenmesinde de yardımcı olur.Beyin fonksiyonlarını geliştirmede önemli rol oynar ve yapılan bazı çalışmalarda Alzheimer hastalarının tedavilerinde kullanılabilir olduğu bildirilmektedir.Fiziksel dayanıklılığı arttırdığı öne sürülen ginseng çayı özellikle atletler tarafından sıklıkla kullanılır. Kronik yorgunluğa ve halsizliğe faydalıdır.Ginseng çayı cinsel performans üzerinde olumlu etkilere sahiptir. Erkeklerde sperm sayısı ve sertleşme probleminin tedavi edilmesine yardımcı olabilir.Kadınlarda yumurta gelişimi ve kalitesine de etkili olduğu bildirilmektedir; ancak bu konularla ilgili çalışmalar yetersizdir.Antioksidan bileşenleri nedeniyle mide, yumurtalık, pankreas, karaciğer ve akciğer kanseri başta olmak üzere diğer kanser türlerinin tedavisinde de önemli rol oynar.Stres ve anksiyetenin tedavisine yardımcı olan ginseng aynı zamanda menopoz belirtilerini hafifleterek ruhsal karmaşıklığın üstesinden gelinmesinde etkilidir. Bu dönemde ginseng çayı kullananlar kendilerini daha rahat ve huzurlu hissettiklerini ve menopoz döneminde oluşan rahatsızlıklarının hafiflediğini söylemektedir.", Yapilisi: "Ginseng bitkisinin çayı, taze ya da kurutulmuş ve toz haline getirilmiş ginseng kökleri kullanılarak hazırlanabilir.Eğer taze ginseng kullanılacaksa zencefile benzeyen ginseng kökleri ince dilimler halinde doğranır ya da rendelenebilir.2 büyük bardak, yani yaklaşık 500 mililitre su kaynatılarak içine 1 yemek kaşığı rendelenmiş ya da 4-5 dilim ginseng kökü kullanılabilir.Kişisel damak zevkine göre bu miktarlar ayarlanabilir.Yaklaşık 5 dakika demlendikten sonra süzülerek içilen ginseng çayını yaparken suyun çok sıcak olmaması önemlidir.Suyun çok sıcak olması ginsengin faydalı etkilerine hasar verebilir.   Biraz soğumaya bıraktıktan sonra demlenmesi önerilen ginseng çayı bal ile tatlandırılabilir ve içine biraz da yeşil çay koyulması farklı bir aroma yaratır.Toz ginseng çayı hazırlanışı için daha dikkatli davranmak gerekir.Toz ginseng tazesine oranla daha yoğundur.500 mililitre çay hazırlamak için yaklaşık 1 tatlı kaşığı toz ginseng yeterlidir.Damak tadına göre ginseng miktarı artırılıp azaltılabilir.")
        caylar.append(ginseng)
        
        let ihlamur = Caylar(Adi: "Ihlamur", Resim: UIImage(named: "ihlamurCayi")!, Faydalari: "Yatıştırıcı özellikleri ile zihinsel stresi ve kaygıyı azalttığı bilindiğinden anksiyete ile mücadelede yardımcıdır.Ruh hali değişimlerinden veya açıklanamayan kronik stresten muzdaripseniz ıhlamur çayının hormon seviyeleriniz üzerinde küçük bir etkisi vardır hem beden hem de zihin için rahatlamayı sağlar.Kronik hastalıkları önler. Antioksidan (kuersetin ve kaempferol) içeriği yüksektir. Bu antioksidan bileşikler serbest radikalleri ortadan kaldırır, hücresel solunumun zararlı yan ürünlerini sisteminizden temizler ve kronik hastalıkları önleyerek genel sağlığı iyileştirir.Vücudu detoksifiye eder. Ihlamur çayında bulunan çok faydalı bir p-kumarik asit bileşiği terlemeyi tetikleyerek vücuttan toksinleri, aşırı tuzlar, yağlar, su ve yabancı maddeleri atmaya yardımcı olur.Ateşi olan bireylerde terlemeyi tetikleyerek ateşin daha hızlı düşmesini sağlar ve organ sistemlerinde kalıcı hasarı önleyebilir.Soğuk algınlığı ve gribi azaltır. Ateşi düşürmek için terlemeyi uyarmanın yanı sıra ağız ve solunum yolu boyunca, burun tıkanıklığını azaltmak, boğaz ağrısı, öksürük ve tahrişe neden olan iltihaplı ve şişmiş zarlar gibi diğer hastalık belirtilerini giderir.İyi bir bağışıklık güçlendiricidir.İltihabı azaltır. Baş ağrısı ve artrit, gut gibi iltihaplı durumlardan muzdarip olanlar için ıhlamur çayı bu ağrılı, şişliğe sebebiyet veren semptomları ortadan kaldırmaya yardımcı olabilir.Solunum yollarındaki iltihaplanmayı azalttığı gibi kan basıncını düşürmeye ve kan damarlarındaki iltihaplanmayı gidermeye yardımcı olur.Sindirimi iyileştirebilir. Mide bulantısı, şişkinlik, kabızlık veya kramp çekiyorsanız 1 fincan ıhlamur çayı midenizi yatıştırabilir.Ihlamurda bulunan bileşikler ve kimyasallar sindirim rahatsızlığını azaltabilir ve yiyeceklerin uygun şekilde sindirilmesi ve atılmasını düzenleyebilir.  ", Yapilisi: "1-2 çay kaşığı kurutulmuş yaprak ve çiçeği bir bardakta kaynar su ilavesiyle 5-10 dk demlendirin. Demlerken üzerinin kapalı olduğundan emin olun. Hazır olduğunda ıhlamuru çıkarın ve isteğe bağlı olarak limon ve/veya bal ekleyin. Biraz soğumasını bekleyip, için. ")
        caylar.append(ihlamur)
        
        let isirgan = Caylar(Adi: "Isırgan Otu", Resim: UIImage(named: "isirganCayi")!, Faydalari: "drar yolu enfeksiyonunu yok etmek için kullanılan ısırgan otu çayı aynı zamanda idrar söktürücü özelliği ile de bilinir.Sindirim dostudur. Midede oluşan şişliklere ve gaz sorunlarına yardım ederek daha rahat bir mideye kavuşmanızı sağlar.Bazı alerjik reaksiyonların tedavisi için doktorlar tarafından tavsiye edilir.İdrar söktürücü özelliğe sahip olduğundan tam bir metabolizma dostudur. Metabolizmanızı hızlandırıcı etkiye sahip olmasıyla, kilo verme sürecinde size yardım eder.C vitamini açısından zengin bir ottur. Soğuk algınlığı dönemlerinizde hazırlayacağınız bitkisel kürlerin başında gelmelidir.İyot açısından da zengindir. Böylece tiroid değerlerinizi ideal noktaya getirir.Kalp ve damar sağlığı için tercih edilmesi gereken bir çaydır.Kanamalara karşı güçlüdür. Mide kanamalarında etkisi görülmüştür.Ergenlik dönemlerinin baş belası akneler için harika bir tercihtir. Isırgan çayını cildinize tonik şeklinde uyguladığınızda, kısa süre içinde aknelerin kaybolduğunu göreceksiniz.Vücudunuzun ihtiyaç duyduğu kalsiyum ve magnezyum değerlerini dengeleyerek, stresli dönemlerinizde sizi sakinleştirici bir etkiye sahiptir.Bol miktarda demir içerdiği için, demir eksikliği tedavisinde etkili bir rol üstlenir.Ağız bakımı için de bitkisel bir çözümdür. Diş çürüklerinden kaynaklanan ağız kokularını giderici özelliğe sahiptir.Doğal aspirindir. Kas ve eklem, hatta baş ağrılarına kadar etkilidir.Ayrıca ısırgan otu çayı saça faydaları ile de bilinir. Saçların sağlıklı uzamasını sağlar ve parlaklık verir. Aynı zamanda ısırgan otu çayı saç dökülmesi sorunlarını da düzenli tüketimde ortadan kaldırabilir.", Yapilisi: "Aktardan aldığınız veya kendi imkanlarınızda toplayıp kuruttuğunuz ısırgan otunu demlemek için sadece sıcak suya ihtiyacınız vardır. Yani ısırgan otu çayı nasıl demlenir endişesi aslında çok kolayca giderilir. Bir bardak ısırgan otu çayı tarifi için 1 çay kaşığı eklemeniz yeterli olacaktır. Yalnız dikkat etmeniz gereken önemli bir nokta var ki o da demlenme süresidir. Yaklaşık 10 dakika boyunca demlenen ısırgan otu çayını içmeniz daha sağlıklı olacaktır. Demini almayan çay; midenizde ağrı yaratırken dilinizde de acı bırakabilir. Bu sebepten dolayı demlerken biraz da sabretmeye ihtiyacınız vardır. Acı tat alırsanız biraz balla tadını hafifletebilirsiniz.")
        caylar.append(isirgan)
        
        let kantaron = Caylar(Adi: "Kantaron", Resim: UIImage(named: "kantaronCayi")!, Faydalari: "Sarı kantaron çayının pek çok yararı bulunmaktadır. Ruh sağlığına çok iyi gelen sarı kantaron çayı aynı zamanda depresyonu de önlemesi ile bilinir. Bunun yanı sıra doğal da bir ağrı kesicidir. Ayrıca sarı kantaron otuna halk arasında binbirdelik otu da denilmektedir. Bunun nedeni bitkinin üzerinde çok sayıda delikler vardır. Sarı kantaron otunun çiçekleri ve kökü çok önemli bir şifa kaynağıdır. Sarı kantaron çayı anti depresan özelliğe de sahiptir. Bunun yanı sıra uykusuzluk, kaygı ve korku gibi durumlarda da sarı kantaron çayı içilebilir. Antiseptik özelliği sayesinde sarı kantaron çayı vücudu da mikroplara karşı korur. O nedenle tüketilmesi önemlidir.", Yapilisi: "Sarı kantaron çayı yapılırken çok dikkatli olunmalıdır. Öncelikle suyun iyice kaynatılması gerekir. Kaynayan suyun içerisine ise 2 ve ya 3 çay kaşığı kurutulmuş sarı kantaron eklenir. Bu şekilde bitki çayı 10 dakika dinlendirilir. İyice demlenen bu çay süzülerek bir bardağa alınır. Hazırlanan çayın içine ise bal ve limon konulur. Çay bu şekilde tatlandırılır. Sarı kantaron çayı fazla demlenirse acı bir tat bırakabilir. Bu nedenle sarı kantaron çayının kısa süre demlenmesi gerekir. Demlendikten sonra ise çay rahat bir şekilde içilebilir")
        caylar.append(kantaron)
        
        let karanfil = Caylar(Adi: "Karanfil", Resim: UIImage(named: "karanfilCayi")!, Faydalari: "Karanfil çayı, sinüslerde oluşan enfeksiyonların hafiflemesine yardımcı olur.Bağırsak hareketlerini hızlandırır. Bu sayede kabızlık ve iltihaplanma sorunlarının önüne geçer.Karanfil çayının içeriğinde bulunan iltihap önleyici bileşenler, aynı zamanda ateş düşürülmesinde de etkilidir.Bağışıklık sistemini güçlendirir, vücut direncini arttırır.Parazit ve mantar önleyici özelliklere sahiptir.Bağırsak parazitlerini yok etmeye yardımcı olur.Eklem ağrılarına karşı etkilidir. Bu yüzden eklem iltihapları tedavisinde etkili rol oynar.Karanfil çayı metabolizmayı uyarır. Böylece kilo vermeye destek olur.İçeriğinde bulunan antioksidanlar, cilt lekeleri, kırışıklık ve yaşlanma belirtilerini önler.Rahatlatıcı etkisiyle kasları gevşetir. Stres düzeyinin azalmasına yardımcı olur.", Yapilisi: "Karanfil çayı için, karanfilleri öğütün ancak toz haline getirmeyin. 1 buçuk su bardağı suyu kaynatın. Su kaynamaya başladığında 5-6 adet öğütülmüş karanfil, tarçın çubuğu ve elma kabuklarını içerisine atın. 5 dakika demlenmesi için bekleyin. Ardından suyunu süzün ve fincana doldurun. Tatlandırmak için 1 tatlı kaşığı bal ilave edebilirsiniz. ")
        caylar.append(karanfil)
        
        let keciboynuzu = Caylar(Adi: "Keçiboynuzu", Resim: UIImage(named: "keciboynuzuCayi")!, Faydalari: "Kemiklerin güçlenmesine yardımcı olan keçiboynuzu çayı, kemik erimesine karşı koruyucu özelliktedir.İçeriğinde yer alan çinko, potasyum ve demir ile kan hücrelerinin yapımında etkili olduğu bilinen keçiboynuzu çayı, aşırı kilo kaybı, kansızlık ve demir eksikliği tedavisinde destekleyicidir.Prostat enfeksiyonlarının tedavi sürecinde etkili olduğu ve erkeklerde görülen cinsel problemleri önlediği düşünülmektedir.Balgam söktürücü özelliği ile akciğeri rahatlatır. Bronşları açar ve nefes alışverişini düzenlemeye yardımcı olur.Çocuk ve yetişkinlerde ishale karşı kullanılan keçiboynuzu çayı, bağırsak parazitlerinin yok edilmesinde faydalıdır.Sindirime yardımcı olan keçiboynuzu çayı, midede yanma ve şişkinlik gibi sorunların azalmasında etkilidir.", Yapilisi: "Keçiboynuzu çayı iki farklı şekilde hazırlanır. Demleme şeklinde yapılan ilk tarifte, 4 – 5 adet yıkanmış keçiboynuzu 1 litre kaynamış suya atılarak 45 dakika bekletilir. Eğer keçiboynuzları suya parçalanarak atılırsa, 20 dakika beklenmesi yeterlidir. Keçiboynuzu çayının diğer bir hazırlama yöntemi ise haşlama yöntemidir. Kaynamakta olan yarım litre suya 5 adet keçiboynuzu atılarak, kısık ateşte 10 dakika kaynatılır. Sonrasında süzülerek sıcak ya da soğuk olarak içilir.")
        caylar.append(keciboynuzu)
        
        let kekik = Caylar(Adi: "Kekik", Resim: UIImage(named: "kekikCayi")!, Faydalari: "Öksürük ve tıkanıklığa iyi gelir. Solunum yolu enfeksiyonlarını azaltır.Anti enflamatuar ve antibakteriyel özelliklere sahiptir.Vertigo, kulak çınlaması, zona ve hepatit gibi birçok hastalığın hafifletilmesine yardımcı olur.Vücuttaki stresin azaltılmasına destek olur.İştahı baskılar. Metabolizma hızını arttırır, yağ yakma sürecine destek olur.Menstrüel krampları ortadan kaldırmaya yardımcı olabilir.Adet ağrılarını ve ruh hali değişimlerini iyileştirmeye destek olur.C vitamini bakımından zengindir. Bu sayede bağışıklığı güçlendirir.Grip, soğuk algınlığı ve nezle gibi hastalıkların daha kısa sürede iyileşmesini sağlar.Kekik çayı beyindeki odaklanma ve hafıza merkezini geliştirir.Kabızlık, şişkinlik, mide bulantısı gibi problemlere karşı iyi gelir.Bağırsak hareketlerinin düzenlenmesinde etkilidir. Mide ağrılarını arttırır.Düzenli tüketilirse toksinlerin vücuttan atılmasına destek olur.Cildin daha pürüzsüz ve canlı görünmesine yardımcı olur.Sivilce ve akne oluşumunun önüne geçer.Cilt çatlakları, cilt lekeleri ve egzamaya karşı etkilidir.", Yapilisi: "Kekiğin çayının yapımı son derece basittir. İçmek istediğiniz miktardan biraz daha fazla suyu kaynatın. İçine 2 dal taze kekik koyduğunuz fincanınızın içine sıcak suyu koyun ve 15 dk. kadar bekleyin. Dilerseniz içine limon ya da bal da ekleyebilirsiniz. Ayrıca bu demleme yöntemiyle daha fazla miktarda çay hazırlayıp cam bir şişede buzdolabına koyabilir ve soğuk olarak da tüketebilirsiniz.")
        caylar.append(kekik)
        
      let kizilcik = Caylar(Adi: "Kızılcık", Resim: UIImage(named: "kizilcikCayi")!, Faydalari: "Kızılcık çayının en bilindik faydası idrar söktürücü özelliğinin olmasıdır. Bu da kişilerde ödem atılmasını sağlar ve şişkinliği giderir.Soğuk algınlığı, grip ve nezle gibi hastalıkların daha hızlı iyileşmesini sağlar.Ağız bulunan yaralar için kızılcık çayını aç karnına tüketmeniz tavsiye edilir. Eğer aç karnına tüketemeyecek durumda iseniz ağzınıza kızılcık çayı alıp bir müddet bekletmeniz fayda sağlayacaktır.Kap damar sağlığının korunmasında etkilidir.Helicopter pylori bakterisi ile savaşma özelliğine sahiptir ve bu nedenden dolayı mide sağlığını koruyucu etkisi vardır.Kilo vermek isteyen kişilerin günlük aç karnına sabah ve akşam kızılcık çayı içmeleri tavsiye edilir.Gut hastalığının belirtilerini hafifletir.Bağışıklık sisteminin kuvvetlenmesinde etkilidir.", Yapilisi: "Kızılcık çayını yapmak için bir litre kaynamakta olan sıcak suyun içerisine verilen ölçülerdeki kızılcık ilave edin. Ardından bir taşım kadar kaynatın ve ocağın altını kapatıp yaklaşık 15 dakika bekletin. Eğer boşaltım sorunu yaşıyor iseniz kızılcık çayını sıcağa yakın olacak derecede ılık içmeniz tavsiye edilir. Aynı zamanda hazırlanmış olan bu çaydan günde 2 fincan içmeniz yeterli olacaktır. Bilhassa kızılcık çayına alışkın değilseniz bir fincandan çok fazla içmemiz bünyenize dokunabilir. Bunun için öncelikle bir fincan ertesi gün ise iki fincan şeklinde uygulamanız sağlığınız açısından daha faydalı olacaktır.")
        caylar.append(kizilcik)
        
        let kirazsapi = Caylar(Adi: "Kiraz Sapı", Resim: UIImage(named: "kirazsapiCayi")!, Faydalari: "Kiraz sapı çayı, zayıflamaya yardımcı oluyor.Antioksidan özellikler gösterdiğinden sindirim sistemi başta olmak üzere birçok soruna iyi geliyor.Karaciğer sağlığını destekliyor.Kiraz sapı çayı ödem attırıcı bir etki oluşturuyor.Bu özelliği sayesinde ödem nedeniyle oluşan şişkinlikleri yok ediyor.Böbreklerin sağlıkla çalışmasını destekliyor.Kötü kolesterolün düşmesine yardımcı oluyor.Damarların yağ, plaka gibi çeşitli maddelerle tıkanmasını engelliyor. Bu sayede kalbin de sağlıkla çalışmasına destek oluyor.Kanın temizlenmesine yardımcı oluyor.Cilt sağlığını da destekleyen kiraz sapı çayı, selülitlerin oluşumunu engelliyor, var olan selülitlerin görünümünü iyileştiriyor.Düzenli olarak kullanıldığında bağışıklık sistemini güçlendiriyor.Sakinleştirici özelliği sayesinde stresle daha kolay baş etmeyi sağlıyor.Buna bağlı olarak stres kaynaklı uykusuzluk problemine de iyi geliyor.", Yapilisi: "Kirazlar tüketildikten hemen sonra kalan sapları kurutmak adına temiz bir kağıt veya tepsinin üstüne iyice yayılmalıdır. Birkaç gün boyunca güneş gören, temiz bir sahada bekletilmesi önemlidir. Kuruyan kiraz sapları, hava almayacak biçimde cam kavanoz içerisine konulabilir. Daha sonra tek kişilik kiraz sapı çayının hazırlanması adına 1.5- 2 su bardağı suyu, cezveye alınmalıdır. Bununla birlikte içerisine bir tutam kiraz sapı eklenerek 5 ile 10 dakika kaynatılmalıdır. Kaynatılan çay içerisinde kiraz saplarını ayırdıktan sonra çayın ılınması beklenmelidir. Daha sonra çay tüketilebilir. ")
        caylar.append(kirazsapi)
        
        let kusburnu = Caylar(Adi: "Kuşburnu", Resim: UIImage(named: "kusburnuCayi")!, Faydalari: "Kuşburnu çayı içerisinde, portakaldan yüzde fazla olmak üzere C vitamini bulunur. Bunun sayesinde bağışıklık sistemi kuvvetlenir. Kolajen yapı sistemine de destek olur.Kuşburnunu çayı, içerisinde yer alan asitler ile mide sorunlarını ve ağrılarını gidermektedir. Hazımsızlık ve şişkinlik gibi sorunlar, kuşburnu çayı içerek giderilebilir. Kuşburnu içerisinde yer alan pektin, kolesterol ve yağı giderir. Fazla karbonhidratı azaltarak kan basıncını düzenli hale getirir.İçinde kafein olmamasına karşın, içen kişiye enerji verir. Gün içinde enerjik, zinde ve dinç olunmasına yardımcı olur.Antioksidan özelliğinden ötürü içerisinde yer alan bol C vitamini, başka mineraller ve vitamin sayesinde grip gibi birçok hastalıktan vücudu korur.Kan dolaşımını düzenler. Bununla beraber kalbi korur. Kalp hastalıklarını, kalp krizini ve anjin gibi durumları önler.Safra kolik, karaciğer nöbetlerini rahatlatmak adına kuşburnu çayı tavsiye edilir. Karaciğer hastalıklarının engellenmesini sağlar.Yanık, yara gibi cilt problemlerine çözümdür. Sürekli olarak tüketildiği zaman antioksidan özelliği ile yaşlanma bulguların ​​​​önüne geçer. Yoğun bir günün akşamında stres atmak için kuşburnu çayı içilebilir. Kuşburnu çayı sinir sistemini rahatlatır.Sinir, migren, yorgunluk ve uykusuzluk kaynaklı ağrıların giderilmesinde oldukça iyidir.Demir konusundan ötürü zengin olmasıyla adet dönemlerinde yaşanan kan kaybının yenilenmesine destek olur. Aynı şekilde hormon seviyesini düzenleyerek, adet ağrısını yatıştırır. Östrojen hormonun çoğalmasını sağlar. Diüretik özelliği ile idrar sorunlarına çözümdür. Kum ve böbrek taşı gibi sorunlara çözüm olabilir. ", Yapilisi: "İlk önce hazır poşet çayının yerine aktarlardan alınacak doğal kuşburnu çayının demlenerek tüketilmesi önerilir. Bunun adına 5 su bardağı çok soğuk olmayan ılık seviyedeki temiz suyu cam bir kase içerisine alınmalıdır. İçerisine havanda ezilen kuşburnu taneleri ilave edilerek 12 saat bekletilmelidir. Bu sürecin sonunda çay, tüketilebilir duruma gelecektir.İçerisine şeker gibi tatlandırıcı eklemeden içmek, kuşburnu çayının sağlık açısından yararlarını arttırır. Eğer daha kolay bir tarif istenirse, öğütülmüş kuşburnunu da kullanılabilir. Bunun adına büyük boy bir bardağa iki çay kaşığı öğütülmüş kuşburnu koymak yeterli olacaktır. Üzerine dökülen sıcak su ile 20 dakika boyunca demlendikten sonra çay, tüketilmeye hazır hale gelecektir. ")
        caylar.append(kusburnu)
        
        let lavanta = Caylar(Adi: "Lavanta", Resim: UIImage(named: "lavantaCayi")!, Faydalari: "Lavanta çayının strese iyi geldiği bilinmektedir. Düzenli kullanımda gerginliği almaya yardımcı olur.Romatizma ağrılarına iyi gelir.Uyku probleminin azalmasına yardımcı olur.Depresyona iyi geldiği bilinmektedir.Sinir sistemine iyi gelir.Tansiyonu dengeleyici özelliği bulunmaktadır.Migren ağrılarını azaltabilir.Mide ve bağırsak sağlığına iyi gelir.Lavanta çayı iştah açıcı bir özelliğe sahiptir.Regl düzensizliklerini düzeltmeye yardımcı olur.Cilt sağlığına iyi gelir. Akne ve sivilcelere karşı cildi iyileştirici özelliği bulunur.Detoks etkisi bulunur.Karaciğer sağlığını olumlu yönde destekler.Temiz saç üzerinde lavanta çayı kullanılırsa saç köklerini besler.", Yapilisi: "Tek kişilik lavanta çayı için, bir bardak kaynatılmış suya, bir çay kaşığı kurutulmuş lavanta eklenir.Lavanta çayı demleme süresi yaklaşık 10 dakika kadardır.Demlenen çay süzülüp içine bir şey eklemeden içilebilir.Tadı acı geliyorsa bal ya da limon ekleyebilir, aromasına farklılık katabilirsiniz")
        caylar.append(lavanta)
        
        let maydanoz = Caylar(Adi: "Maydanoz", Resim: UIImage(named: "maydanozCayi")!, Faydalari: "Maydanoz çayı, güçlendirici ve ödem söktürücü özellikler ile soğuk algınlığı, enfeksiyon hastalıkları gibi pek çok hastalıktan korunmaya yardımcı olur.Maydanoz çayı, vücutta bulunan toksin ve ödemleri hızlı bir biçimde söker. Bu özelliği sayesinde kilo vermede oldukça başarılıdır.C vitamini açısından çok zengin bir içeriğe sahip olan maydanoz, bilhassa kış mevsiminde bağışıklığı güçlendirip, hasta olma riskini azaltır.Maydanoz çayı, cilt bakımı konusunda da oldukça başarılı bir çaydır. Sürekli şekilde içilen maydanoz çayı; akne, ciltte oluşan sivilce, kaşıntı, dökülme gibi sorunların tedavisi açısından önemli rol oynar.Maydanoz çayının karaciğer adına da oldukça yararlı olduğu kanıtlanmıştır. Bu çay, kan şekerini düzenleme konusunda da çok başarılıdır.Sakinleştirici özelliğe sahip olan maydanoz çayı, sürekli bir şekilde tüketildiği takdirde, stres ve sıkıntıdan arınmaya yardımcı olacaktır. ", Yapilisi: "Maydanoz çayının hazırlanması adına ilk önce maydanozlar seçilmelidir. Yaprak ve sap kısmı birbirinden ayrılmalıdır. Her bardak adına yaklaşık olarak bir şeker kaşığı maydanoz yaprağı hazırlanmalıdır.Yapraklar bir demlik içerisine alınarak suyla kaynatılmalıdır. Yapraklar yaklaşık olarak dört dakika boyunca demlenmelidir. Maydanoz yapraklarını süzdükten sonra çay tüketilmeye hazır hale gelecektir. Bununla beraber maydanoz saplarıyla da maydanoz çayını hazırlamak mümkündür. ")
        caylar.append(maydanoz)
        
        let melisa = Caylar(Adi: "Melisa", Resim: UIImage(named: "melisaCayi")!, Faydalari: "Hazımsızlık, şişkinliği ve sindirim sistemi ile ilgili sıkıntıları giderir.Melisa otu suyu ya da yağı cildin yenilenmesine yardımcı olur.Melisa otunu kaynatılıp elde edilen suyla saçlar yıkandığında kepeklenme ve dökülmenin sorunlarını giderir.Saçların mat görünümünü giderip parlak ve sağlıklı görünüm sağlar.Menstürasyon dönemlerindeki (adet dönemi) sancıların ve krampların giderilmesini sağlar.Cilt kırışıklıklarını azaltır ve cildi canlandırır, yaraların hızla iyileşmesine yardımcı olur.Akne sorunlarını giderir.Kan şekerinin düşürülmesini sağlar.İdrar söktürücü özelliği bulunmaktadır.Kan dolaşımının düzenlenmesini sağlar.Karaciğer ve safra kesesi sorunlarını giderir.Migren ataklarında doğal bir kür olarak kullanılabilir.Kronik uykusuzluk şikayetini giderir.Stres, kaygı, duygu durum bozukluklarını azaltır.Depresyona karşı etkilidir.Beyin fonksiyonlarını artırarak hafızayı güçlendirir.Uçuk için doğal ilaçtır.Sindirimi kolaylaştırır.", Yapilisi: "Melisa çayını iki farklı şekilde yapabilirsiniz. Eğer poşet çay olarak aldıysanız, bir fincan suyu kaynatın. Kaynayan suya melisa çayı poşetini ekleyin ve 2-3 dakika bekleyin. Ardından şeker ekleyerek içebilirsiniz.Kurutulmuş melisa kullanacaksanız, 1 buçuk fincan suyu kaynatın. Su kaynadığında içerisine 1 çay kaşığı kurutulmuş melisa koyun ve demlenmesi için 5-6 dakika bekleyin. Çay demlediğinde süzerek fincana alın. İsteğe göre 1 tatlı kaşığı bal ekleyerek tatlandırabilirsiniz.")
        caylar.append(melisa)
        
        let nane = Caylar(Adi: "Nane", Resim: UIImage(named: "naneCayi")!, Faydalari: "Nanenin mide spazmlarına ve genel mide rahatsızlılarına iyi geldiğine dair bazı kanıtlar vardır.Nane tüketimi enerjinizi artırabilir.Nane çayı kronik ağrılar için iyileştirici etki yaratabilir.Nane tüketiminin irritabl bağırsak sendromununu azalttığı görülmüştür.Nane içeriğindeki mentol sayesinde zihninizin stresten uzaklaşmasına yardımcı olabilir.Nane tüketiminin sinüslere iyi gelerek solunum problemlerini azalttığı görülmüştür.Nane çayının menstrüal ağrılara iyi geldiği bazı kadınlarda görülmüştür.Alerji ve astım belirtilerini azalttığı görülmüştür.", Yapilisi: "Nane çayını marketlerden poşet çay şeklinde alabilirsiniz. Bunun yanında aynı zamanda aktarlardan nane yaprağı alarak evinizde de demleyebilirsiniz. Nane çayını hazırlamak için 6 ile 8 bardak arası sıcak suyun olduğu demliğe poşet çayını veya nane yapraklarını ilave edip ve 4 veya 6 dakika bekletiniz. Sonrasında nane çayınıza isteğinize bağlı olarak biraz limon ve bir miktar şeker ile de tatlandırma imkanınız vardır. Ancak şeker zararlı bir gıda olduğu için şekersiz içmeniz veya şeker yerine bir tatlı kaşığı bal atmanız daha sağlıklı olacaktır")
        caylar.append(nane)
        
        let nar = Caylar(Adi: "Nar Çiçeği", Resim: UIImage(named: "narCayi")!, Faydalari: "Nar çiçeğinin metabolizmaya olan etkisinden söz etmek gereklidir.Sindirim sistemini kontrol altına alır ve kabızlık durumunu önler ishale de fırsat vermez.Bağırsaklarınızın sistemli şekilde çalışmasını sağlar.Narın antioksidan bir meyve olduğunu hatırlayın. İşte nar çiçeği de aynı özelliğe sahiptir.Antioksidan etkisi ile vücudu temizler ve zararlı maddelerin atılmasını sağlar.Nar çiçeğinden elde edilen nar çiçeği çayı bitki çayı saatlerinizi lezzetlendirebilir.Yüksek tansiyon hastaları için doktor onayı ile tüketildiğinde tansiyonun yükselmesini önler ve dengede tutar.Nar çiçeği çayı faydaları arasında iltihap sökücü özelliği de yer alır. Bu özelliğini enfeksiyon günlerinde fark edebilirsiniz.İdrar yolu enfeksiyonu ve kış enfeksiyonu yaşadığınızda gün içinde bir fincan nar çiçeği çayı tüketmeyi ihmal etmeyin.Hücre yenileyici özelliği ile dikkat çeken nar çiçeği, yara oluşumunu önler ve cildinizdeki yaraların çabuk iyileşmesine destek olur. Böylece cildiniz daha sağlıklı bir görünüme kavuşur.Sindirim sistemi için faydalı olan nar çiçeği çayı, diyet beslenmesinde tüketildiğinde yağ yakımını hızlandırıcı etkisini gösterecektir. Ödemden kurtulmak için günde bir fincan içebilirsiniz.Günümüzün en sık yaşanan hastalıklarından biri olan kanser için nar çiçeği çayı ile kendinizi koruma altına alabilirsiniz. Çünkü nar çiçeği çayı kanserli hücrelerin yayılmasını önler.Böbreklerde taş oluşumu ve enfeksiyon nar çiçeği çayı ile giderilebilir. Böbrek sağlığını korumaktadır.Nar çiçeğini bir suda bekletip bu su ile gargara yaparsanız, ağız içindeki bakteriyi ve kötü kokuyu yok edebilirsiniz.Mikrop kırıcı özelliğini ağız bakımında da gösterecektir.C vitamini açısından zengin olan nar çiçeği çayı ile vücut direncini her zaman güçlü tutabilirsiniz.İleri yaşlarda görülen damar sertliği ve kireçlenme problemine karşı önlem almak için nar çiçeğinden faydalanabilirsiniz.", Yapilisi: "Hazırlamak için yaklaşık 1 litre kadar içme suyunu kaynatın.Kapaklı bir sürahi içine 2 yemek kaşığı kuru nar çiçeğini ekleyin ve kaynayan suyu sürahiye boşaltın.Yaklaşık 8 dakika kadar demlenen bitki çayınızı süzerek bardaklara servis edin. Geçen 8 dakika içinde çayınızın rengi değişecek ve kırmızı bir renk alacaktır. Nar çiçeği çayı şifa dağıtmak için hazır! Hastalıklara karşı hassas bir vücudunuz varsa nar çiçeği çayınızın içine bir adet çubuk tarçın ve birkaç adet karanfil ekleyip etkisini daha da güçlü hale getirebilirsiniz. Mide hastalıkları yaşayanların ve hamilelik döneminde olan kadınların doktora danışıp tüketmesi tavsiye edilmektedir.")
        caylar.append(nar)
        
        let okaliptus = Caylar(Adi: "Okaliptus", Resim: UIImage(named: "okaliptusCayi")!, Faydalari: "Soğuk algınlığı semptomlarının hafifletilmesinde yardımcı olur.Balgam söktürür ve öksürüğü tedavi eder.Okaliptus çayı bakteri ve mantarların neden olduğu enfeksiyonları giderir.Sakinleştirici ve yatıştırıcı özelliği vardır.Kan şekerini düzenler.", Yapilisi: "Okatiptus çayı taze ya da kurutulmuş okaliptüs yapraklarından demlenir. 1 tutam okaliptüs yaprağının üzerine kaynatılmış bir bardak su eklenip 10 dakika kadar demlendirilir. Okaliptus çayı günde 2 veya 3 kez tüketilebilir.")
        caylar.append(okaliptus)
        
        let papatya = Caylar(Adi: "Papatya", Resim: UIImage(named: "papatyaCayi")!, Faydalari: "Papatya çayı uykusuzluğa iyi gelmekte ve uyku kalitesini artırmaktadır. Gaz ve bulantı gibi sindirim sistemi şikayetlerini yatıştırabilmekte; antiinflamatuar etkisi sayesinde diyare ve mide ülserine karşı koruyucu etki gösterebilmektedir. Yine antiinflamatuar etkisi sayesinde bazı kanser türlerine karşı koruyucu olabileceğine dair çalışmalar da bulunmaktadır. Özellikle öğünlerle birlikte tüketildiğinde kan şekeri kontrolünü sağlamaya yardımcı olan papatya çayı, içerdiği antioksidanlar sayesinde kan basıncı ve kan kolesterol düzeylerinin kontrol edilmesine katkıda bulunarak kalp hastalığı riskini azaltmaktadır.", Yapilisi: "2-3 yemek kaşığı kurutulmuş papatya çiçeğinin üzerine yarım litre kaynar su ekleyin. 3-5 dakika demlenmesini bekleyin. Daha sonra papatyayı süzerek çayınızı içebilirsiniz. Tatlandırmak için bal ya da bir kaç damla limon ekleyebilirsiniz. Bazı rahatsızlıklarda daha önce de belirttiğimiz gibi çayın hazırlanış şekli değişebilir.")
        caylar.append(papatya)

        let rezene = Caylar(Adi: "Rezene", Resim: UIImage(named: "rezene")!, Faydalari: "Rezene çayı, rezene bitkisinin içerdiği yağ asitleri sayesinde antidiyabetik ve antioksidan etkiye sahiptir. Antioksidan etkisi ile hücre hasarını önlemeye yardımcı olmakta, yeni hücrelerin oluşumunu desteklemekte ve yaşlanmayı geciktirici etki sağlamaktadır. Ayrıca bakteri ve mantar enfeksiyonları ile savaşmaya yardımcı olmaktadır. Kan pıhtısı oluşumunu engellemekte, kadın üreme sistemini destekleyerek anne sütü salgılanmasına katkıda bulunmaktadır. Rezene çayı ağız kokusuna iyi gelmekte, nefesi tazelemektedir. Ayrıca sindirim sistemi kaslarını rahatlatarak bağırsak hareketlerini düzenlemekte ve kabızlığa iyi gelmektedir.", Yapilisi: "ağlığa pek çok faydası ve hastalıkları önleme konusunda etkili olduğu düşünülen rezene çayı, demlenmeye hazır poşetler hâlinde satın alınarak sıcak suyla kolayca demlenebileceği gibi aktardan alınan rezene yaprağı ve tohumları ile de hazırlanabilir. Bir cezvede su kaynatılırken başka bir kapta, 1 su bardağı rezene çayı için 1 çay kaşığı rezene tohumu ezilir. Su kaynamaya başladığında ezilen tohumlar cezveye atılır. Arzuya göre rezene yaprağı da koyulabilir. Çay, bir-iki dakika kadar kısık ateşte kaynadıktan sonra ocak kapatılır ve 5 dakika kadar demlenmesi için bekletilir. Cezvedeki rezene çayı süzülerek fincana alınır ve soğumadan tüketilir. Tüm bitkisel çaylarda olduğu gibi rezene çayı da dikkatli ve az miktarda tüketilmelidir. Aşırı tüketimi sağlığa zararlı olabilir. Kusma, baş ağrısı ve alerji gibi yan etkileri görülebilir. Medikal ilaçlarla birlikte tüketilmeden önce hekime danışılmalıdır. Gebelerin ve yaşlıların, rezene çayı ve diğer bitki çaylarını tüketmeden önce mutlaka hekimden görüş alması gerekir.")
        caylar.append(rezene)
        
        
        let safran = Caylar(Adi: "Safran", Resim: UIImage(named: "safranCayi")!, Faydalari: "Depresyon tedavisinde etkilidir. Bitki hakkında yapılan klinik çalışmalar, safranın hafif şiddetli depresyona iyi geldiği hakkında bilgiler sunar. 6 hafta boyunca 40 kişi üzerinde yapılan araştırmalarda, düzenli olarak ve belli miktarda kullanılan safranın, kişilerde psikolojik yönden iyileşme sağladığı görülmüştür.Aynı araştırmada kadınların adet öncesi sendromları ile ilgili çalışmalar da yapılmış ve safran çayının, bu sendromları hafiflettiği sonucuna varılmıştır.Kalp ve damar sağlığına faydalı olduğu hakkında görüşler bulunur. Geleneksel tıpta safran çayı kalp hastaları tarafından kullanılan bir çaydır. Yapılan bazı araştırmalar, antioksidan özellik taşıyan safranın, kan basıncını düşürdüğünü ve kalbin zorlanmasını engellediğini göstermiştir. Fakat bu araştırmalar az sayıda olup yeterli düzeyde değildir. Safranın, kandaki kolesterol ve trigliserid seviyelerinin düşmesine etki ettiği hakkında görüşler de mevcuttur.Küçük çaplı yapılan bazı araştırmalarda, safranın sağlıklı hücre gelişimine katkı sağladığı hakkında bilgilere ulaşılmış olup bu araştırmalar tam netlik kazanmamıştır. Kanserli hücre oluşumunu azalttığı hakkında bazı görüşler mevcuttur.Safranla ilgi yapılan bir diğer klinik araştırma, göz sağlığına olan katkıları hakkındadır. Bu çalışmalar sırasında bitkinin, retinaya olan kan akışını artırdığı ve retina hasarlarının giderilmesinde faydalı olabileceği görülmüştür. Yaşa bağlı gelişen makula bozulmalarında da kullanılabileceği konusunda bilgiler elde edilmiştir.Safran çayı geleneksel olarak halk arasında, sedef hastalığının tedavisinde, ağrı hafifletici ve enfeksiyonu önleyici olarak da kullanılır.Safranın içerisinde yüz elli kadar uçucu bileşik vardır. Bu nedenle tedavi edici özelliğe sahiptir. Safran çayı faydası olan şifalı bir bitki çaydır.", Yapilisi: "Safran çayı hazırlanışı diğer bitki çayları gibidir. Kaynatarak değil, demleme yöntemiyle yapılır. Kısaca şöyle tarif edilebilir:Bir bardak safran çayı hazırlamak için, 6-7 adet safran bitkisine gereksinim vardır.Önce kullanılacak su kaynatılır.Kaynama bitince birkaç dakika dinlendirilir.Sonra da içine safran ipleri konmuş olan bardağın üzerine dökülür.Beş dakika kadar demlenmeye bırakılır.Su amber rengini aldıktan sonra süzülerek içilir.Bazı tariflerde, safran çayı içindekiler safran iplerinin yanında başka baharatlar da içerebilir. Kabuk tarçın, kakule, zerdeçal ve benzeri baharatlar kullanılarak hazırlanan çay tarifleri de mevcuttur. Safran çayını dilerseniz bal ile tatlandırarak tüketebilirsiniz.")
        caylar.append(safran)
        
        let sarimsak = Caylar(Adi: "Sarımsak", Resim: UIImage(named: "sarimsakCayi")!, Faydalari: "Antibakteriyel özelliğe sahip olan sarımsak çayı midedeki zararlı bakterilerin yok edilmesini sağlayarak mide rahatsızlıklarına engel olabilir.Gece yatmadan önce tüketilen sarımsak çayı içeriğindeki aromatik yağların etkisi ile göğüs tıkanıklıklarını önleyerek rahat bir uyku geçirilmesini sağlamaya yardımcı olur.Antioksidan özeliklere sahip olan bitkisel çay ciltte oluşan mantar, sivilce ve akne gibi problemlerin ortadan kaldırılmasında etkin rol oynar.Yüksek vitamin ve mineral içeriği sayesinde bağışıklık sistemini güçlendirerek vücudu hastalıklardan korur.Kış aylarında görülen soğuk algınlığının ve enfeksiyona bağlı hastalıkların tedavisinde önemlidir.Hazırlanan sarımsak çayı saç diplerine masaj yapılarak uygulandığında saç derisinin ve saç köklerinin canlanmasını sağlar ve aynı zamanda saç kırıklarını önleyici etki gösterir.Sarımsak çayı buharı sinüslerin açılmasını sağlayarak sinüzit tedavisinde etkin bir rol oynar.Gıda zehirlenmesi durumunda antibiyotik etkisi midenizi rahatlatacaktır.Açık yara, kesik ve iltihapları iyileştirir.Kalp ve damar sağlığının korunmasında etkili olan sarımsak çayı özellikleri sayesinde kalp krizi riskini en aza indirir.Kanserli hücrelerin yayılmasını engeller.Alzheimer hastalığının oluşmasını önler.Antioksidan özelliği sayesinde vücuttaki toksinleri atmaya yardımcı olur ve yağ yakımını hızlandırır.", Yapilisi: "arımsak çayı hazırlığı için öncelikli olarak zencefiller robot ya da havan yardımıyla parçalanarak toz haline getirilir.Toz haline getirilen zencefillerin üzerine 1,5 su bardağı su ilave edilerek 2-3 dakika kadar kaynatılır.Zencefillerin uzun süre kaynatılması içeriğindeki yararlı maddelerin kaybına neden olabilir. Bu yüzden zencefilleri birkaç dakika kaynatmak yeterlidir.3 diş sarımsak havanda ezilir ve zencefilli kaynamış suya eklenir.Sarımsaklar eklendiğinde ocağın altı kapatılmalıdır.Sarımsak da eklendikten sonra pişirme kabının üstü temiz bir bez ile örtülür ve 10 dakika dinlenmeye bırakılır.Dinlendirilen sarımsaklı zencefil karışımı ocaktan alınır ve bardağın içine süzülür.Bardaktaki sarımsak çayı üzerine limon suyu eklenerek tüketilebilir.Aroması keskin gelirse balla tatlandırarak sarımsak çayınızı içebilirsiniz.")
        caylar.append(sarimsak)

        let tarcin = Caylar(Adi: "Tarçın", Resim: UIImage(named: "tarcinCayi")!, Faydalari: "Özellikle kış günlerinde grip, soğuk algınlığı gibi hastalıklara karşı vücudu korur.Sindirim sisteminin düzenli çalışmasına destek olur.Kan dolaşımını hızlandırır.Mide bulantısına ve kusmaya karşı etkilidir.Kan şekerini düzenler. Şeker krizi nedeniyle ortaya çıkan el ve ayak titremelerini azaltmasıyla bilinir.Gaz söktürücü özelliği vardır. Midede oluşan şişkinliğe iyi gelir. Hafızayı güçlendirir. Parkinson ve alzheimer gibi hastalıkların tedavisine destek olur. Mide kanseri başta olmak üzere bazı kanser türlerine karşı etkilidir. Kanserli hücrelerin büyüyüp çoğalmasını engeller.Diş eti hastalıklarına ve diş çürüklerine karşı etkilidir.Tarçının iltihapları giderici etkisi de mevcuttur.Metabolizmayı hızlandırmasıyla da bilinir.", Yapilisi: "Bir demlikte 2 su bardağı suyu kaynatın.Kaynama suyunun içerisine 2-3 dilim elma ve yıldız anason ekleyin. Bir fincanın içerisine 1 çay kaşığı toz tarçın ya da 2 adet kabuk tarçın ekleyin. (Yalnızca biri seçilmelidir.)Kaynayan suyu, tarçının üzerine ekleyin. 10 dakika demlenmeye bırakın. Demlenen tarçın çayını tatlandırmak için 1 tatlı kaşığı bal ekleyebilirsiniz.")
        caylar.append(tarcin)

        let zencefil = Caylar(Adi: "Zencefil", Resim: UIImage(named: "zencefilCayi")!, Faydalari: "Mide bulantısına karşı zencefil çayı tüketebilirsiniz. Zencefil çayı var olan ve sürekli olarak mide bulantısı şikayeti yaşayan kişiler için tüketilen bir çaydır. Bundan dolayı mide bulantısına karşı zencefil çayı tüketebilirsiniz. Zencefil çayı mideyi yatıştırır ve bulantıya neden olan faktörleri ortadan kaldırır.Deniz yolculuklarında sürekli olarak deniz tutmasına maruz kalıyorsanız yine zencefil çayı tüketebilirsiniz. Zencefil çayı deniz tutmasına karşı oldukça faydalıdır. Rahat ve konforlu bir yolculuk geçirmek istiyorsanız zencefil çayı tüketmelisiniz.Baş dönmesi şikayetleri için de yine zencefil çayının tüketilmesi önerilmektedir. Sürekli olarak baş dönmesi şikayeti yaşıyorsanız zencefil çayı tüketerek bu şikayetlerin önüne geçebilirsiniz. Zencefil çayı baş dönmesine sebep olan kötü faktörleri ortadan kaldırır ve kişinin gündelik hayatını oldukça fazla etkileyen baş dönmesini bitkisel yollardan tedavi eder.Vücutta yer alan kronik ağrıları da dindirir. Zencefil çayının hafif rahatlatıcı etkisi vardır. Bundan dolayı sürekli olarak kronik ağrılar yaşayan bir kişinin zencefil çayı içmesi önemlidir. Kronik romatizma ağrıları ve diğer ağrıları zencefil çayı tüketerek kolayca dindirebilirsiniz. Zencefil çayı bundan dolayı en fazla tercih edilen bitkisel çaylardan biridir.Kas ağrıları yaşayan kişiler için de yine aynı şekilde zencefil çayı tüketilmesi önerilir. Zencefil çayı her türlü ağrıyı dindirici özelliği bulunduğundan ötürü özellikle kas ağrıları yaşayan kişiler için de tüketilmektedir. Zencefil çayı sindirimi hızlandırır. Böylece sindirim hastalıklarının önüne geçer. Aynı zamanda sindirime bağlı olarak kilo alınmasını da engeller. Zencefil çayı tüketmek bağırsakların da hızlı çalışmasını sağlar. Böylece aşırı kilo alımının önüne geçilir.Solunum yollarında yer alan iltihap ve diğer rahatsızlıkların önüne geçer. Zencefil çayı solunum yollarını açar ve kişinin daha rahat nefes alıp vermesini sağlar.", Yapilisi: "Zencefil çayını yapmak için öncelikle zencefilin dış kabuğunu soyarak işe başlamalısınız. Zencefilini dış kabuğunu soyduktan sonra 1 su bardağı suyu kaynattıktan sonra üzerine zencefil ekleyiniz. Ardından yaklaşık olarak 5 ila 10 dakika kaynattıktan sonra bu çaya isteğe bağlı olarak bal da ekleyebilirsiniz. Bal eklemeniz durumunda zencefil çayı iyi bir öksürüğe karı bitkisel çay olacaktır. Bu şekilde zencefil çayınız artık hazırdır. Afiyetle tüketebilirsiniz.")
        caylar.append(zencefil)
        
        
        let zerdecal = Caylar(Adi: "Zerdeçal", Resim: UIImage(named: "zerdecalCayi")!, Faydalari: "Kanseri önlemeye yardımcı olur.Bağışıklık sistemini güçlendirir.Alzheimer’a karşı koruyucudur.Artrit semptomlarını hafifletir.Kolesterolü düşürür ve kalp sağlığını korur.Sindirim sistemini destekler.", Yapilisi: "Zerdeçalın içindeki en önemli ve en etkin madde olan kurkumini en iyi şekilde alabilmenin yolu, zerdeçal çayı tüketimidir. Düzenli olarak zerdeçal çayı tüketerek kurkuminin vücuda sağladığı faydaları almak mümkün olur. Bu sebeple de zerdeçal çayı tüketmeye özen göstermek gerekir.Zerdeçal çayı demlemek için; 1 adet zerdeçal kökü veya tozu, 2 su bardağı su, 1 çay kaşığı zerdeçal, çeyrek limon, 1 tatlı kaşığı bala ihtiyaç var.Zerdeçal çayı hazırlamak için zerdeçal kökü kullanılacaksa kökü parçalayarak toz haline getirmek gerekiyor. Zerdeçal tozu kullanılacaksa da 1 çay kaşığı yeterli olur. Zerdeçal çayı hazırlarken öncelikle 2 bardak su kaynatılır. Su kaynadıktan sonra parçalanıp toz haline getirilen zerdeçal kökü veya 1 çay kaşığı zerdeçal tozu kaynayan suyun içine eklenir. İçine 1 çay kaşığı zerdeçal katılır. Ağzı kapalı bir şekilde 10 dakika demlenmesi beklenir ve ılık olarak içilir. Zerdeçal çayını sade olarak tüketmek biraz acı gelebilir. Bu sebeple çayın içine bal ve limon da eklenebilir. Bu şekilde tüketimi daha lezzetli olacaktır.")
        caylar.append(zerdecal)
        
    }
}
