//
//  YaglarViewController.swift
//  BirTutamSaglik
//
//  Created by GAMZE AKYÜZ on 14.04.2022.
//

import UIKit

class YaglarViewController: UIViewController,UITableViewDelegate,UITableViewDataSource {

    @IBOutlet weak var tableView: UITableView!
    var yaglar = [Yaglar]()
    var yagSec : Yaglar?

    override func viewDidLoad() {
        super.viewDidLoad()
        yagEkle()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return yaglar.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.text = yaglar[indexPath.row].adi
        return cell
    }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        yagSec = yaglar[indexPath.row]
        self.performSegue(withIdentifier: "toYaglarDetayViewController", sender: nil)
    }
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "toYaglarDetayViewController"{
            let destinationVC = segue.destination as! YaglarDetayViewController
            destinationVC.selectedYaglar = yagSec
        }
    }
    
    func yagEkle(){

        let acibadem = Yaglar(Adi: "Acıbadem Yağı", Resim: UIImage(named: "acibadem")!, Faydalari: "Faydaları : Kabızlığı giderici özellikleri ile bilinen aynı zamanda bedenin ve zihnin yorgunluğunu gidermede faydalıdır. Göğüsün yumuşamasına yardımcı olmanın yanı sıra öksürüğün kesilmesine de faydalıdır. Genellikle cilt bakımında kullanılan acı badem yağı kadınların ilk tercihleri arasında yer almaktadır.Acı badem yağı genellikle cildi güzelleştirme, cildi gençleştirme, ciltteki hücrelerin yenilenmesini ve cilt bakımı için oldukça faydalı olan bir yağdır. Kuru ciltler için çok iyi nemlendirme özelliğine sahip bitkisel yağlar arasındadır.", KullanimSekli: "Nemlendirici olarak: Acıbadem yağı hassas ciltler için mükemmel bir nemlendiricidir. Gün içerisinde 2-3 defa rahatlıkla kullanılabilir.Ekstra kuru bölgelere uygulanabilir: Acıbadem yağı dirseklere, ayaklara ve kurumaya eğilimli diğer bölgelere sürülerek nemlendirme sağlanır. Bu yöntem ile çok kısa sürede kuruyan cilt, yerini daha gergin ve canlı bir cilde bırakır.Ev yapımı bir saç maskesi yapmak için: Acıbadem yağı, avokado ile karıştırılır ve ardından nemli saça yedirilir. Çok kısa zamanda gözle görülür şekilde sonuçlar alınacaktır.Esansiyel yağlarla birleştirmek için: Cilde uygulanan esansiyel yağları seyreltmek için taşıyıcı yağ olarak acıbadem yağı kullanılmalıdır.Doktorunuza danışarak suyun içerisine damlatarak içebilirsiniz.")
        yaglar.append(acibadem)

        let anason = Yaglar(Adi: "Anason Yağı", Resim: UIImage(named: "anasonyagi")!, Faydalari: "Şişkinlik giderici, gaz söktürücü, mide hazımsızlığını giderici, anne sütü arttırıcı, selülit tedavisinde ve son olarak da uyku düzenlemeye faydalı bitkisel yağlar arasındadır.", KullanimSekli: "Anason yağının içerisinde bulunan antiseptiklerin, yaraları kuvvetli bir şekilde iyileştirici etkisi bulunmaktadır. Ancak yara üzerine sürülecek olan anason yağı seyreltip kullanılmalıdır. Aksi takdirde ters bir etki yaratabilir.Anason yağı kan dolaşımını arttırarak romatizmal hastalıklara iyi gelmektedir.Seyreltilerek ağrılı dizlere sürülebilir.Anason yağı suyuyla hazırlanan buhar banyolarının balgam söktürücü etkisi olduğu biliniyor.Çocuklarda karın ve topuk bölgelerine seyreltilerek sürülmesi gereklidir. Günde 2 defa, 2-3 damla bir şeker parçasına ya da bir fincan suya damlatılarak kullanılabilir. Daha fazla kullanılması sakıncalıdır.")
        yaglar.append(anason)

        let ardic = Yaglar(Adi: "Ardıç Yağı", Resim: UIImage(named: "ardicyagi")!, Faydalari: "İştah açıcı olması ile birlikte aynı zamanda idrar söktürücü ve mide ağrılarında, saç dökülmesinde, boğaz iltihaplarında, kanda ki şeker oranının düşürülmesinde, deri hastalıklarında, selülit tedavisinde, kramplarda, romatizmalarda, egzamaya faydalı olan bitkisel yağlar arasındadır.", KullanimSekli: "Ardıç yağı kesme şeker üzerine 5 damla kadar damlatıldıktan sonra dil üstüne koyulur. Bu, vücuttaki yabancı maddelerin ve cildin güzelleşmesine fayda sağlar. Burun deliklerine üzerine ardıç yağı damlatılan pamuklar yerleştirildikten sonra 15 dakika kadar nefes alınır ve bu uygulama günde 1 ya da 2 defa yapılabilir. Krem ya da merhem olarak ağrıyan eklem ve kaslara da sürülebilir. 1 damla kadar ağrı üzerine damlatılması yeterli olur. ")
        yaglar.append(ardic)

        let aspiryagi = Yaglar(Adi: "Aspir Yağı", Resim: UIImage(named: "aspiryagi")!, Faydalari: "İçeriğinde yer alan antioksidan bileşenler bağışıklık sistemini güçlendirerek vücudun enfeksiyonlara karşı savaşını destekler. Kanser hücresi oluşumunu engeller ve oluşan hücrelerin yok edilmesini sağlar. Özellikle meme ve prostat kanserini önleyici etkiye sahiptir.Kolesterol düzeyini dengede tutarak vücudun yağ metabolizmasını düzenler. Kalp krizi riskine karşı vücudu korur.Omega 6 yağ içeriği sayesinde diyabet hastalığının tedavisini destekleyici rol oynar. Kan şekerinin dengelenmesini sağlayarak insülin direnci gelişmesini önler ve diyabet hastalığı riskini ortadan kaldırmaya yardımcı olur.Nefes darlığını önleyici özelliğe sahip olan aspir yağı öksürüğe de faydalıdır ve ayrıca etkili bir balgam söktürücüdür.Sindirim sistemi üzerinde olumlu etkilere sahip olan aspir yağı bağırsak hareketlerini hızlandırarak kabızlığı önler.Saç köklerinin beslenmesine destek olan aspir yağı saçların çabuk uzamasını sağlar ve daha canlı bir görünüm kazandırır.Romatizmal ağrıların hafiflemesine yardımcıdır.", KullanimSekli: "Romatizma hastaları bacaklarına masaj ile birlikte aspir yapı uygulayabilirler. Böylece kan dolaşımı hızlanır ve iltihaplar vücuttan atılır.Besin olarak kullanılmak istenirse salataların içine eklenebilir. Aspir yağı ısıya dayanıklı değildir ve bu nedenle ısıtılmadan soğuk haliyle yemeklere eklenmesi önerilir.Bronzlaştırıcı etkiye sahip olan aspir yağı yaz aylarında güneş kremi olarak da kullanılabilir.Düzenli olarak tüketilen aspir yağı stres nedeniyle gelişen depresyonun tedavisine yardımcı olur. Seratonin düzeyini artırır ve Alzheimer hastaları için önerilen bir yağ çeşididir.Yatmadan önce temiz bir cilde birkaç damla aspir yağı ile masaj yapılır. Aspir yağı kullanımı hangi amaçla tüketileceğine göre değişiklik gösterir. Saçların daha canla ve parlak görünmesini sağlamak amacıyla birkaç damla aspir yağı avuç içine dökülerek saçlar yıkandıktan sonra saç diplerine masaj yaparak kullanılır.")
        yaglar.append(aspiryagi)

        let atkestanesi = Yaglar(Adi: "At Kestanesi Yağı", Resim: UIImage(named: "atkestanesi")!, Faydalari: "At kestanesi ile yapılan kremler kırışıklıkların azalmasında büyük rol oynuyor.Ciltte oluşan geniş gözeneklerin giderilmesini sağlıyor.Ciltte ve yüzde oluşan kırmızı kılcal damarların giderilmesinde etkili.Romatizmadan kaynaklı ağrıların hafiflemesini sağlıyor.Saçların dökülmesini önlüyor.Kas ağrılarını dindiriyor.Göğüslerin toparlanarak sarkmasını önlüyor.Güneş lekelerini hafifletiyor.Varis tedavisine yardımcı oluyor.Boyun bölgesini toparlayarak gevşemeyi önlüyor.Sivilce tedavisinde başarılıdır.Nezle ve gribi tedavi edicidir.Tüm vücutta kaynaklanan iltihabın kurumasını sağlar.Kılcal damarların kanama ve çatlamasını iyileştirirken iç kanamanın geçmesini sağlar.Göğsü yumuşatarak öksürüğü hafifletir.", KullanimSekli: "At kestanesi yağının en kolay uygulama şekli vücuda masaj şeklinde uygulanması olmaktadır. At kestanesi yağı cilt için maske şeklinde uygulanabilmektedir. At kestanesi yağı eklem ağrılarında uygulandığında sarılarak bekletilmektedir. At kestanesi yağı kan dolaşımına iyi geldiği için bacaklar için masaj ile kullanılmaktadır. At kestanesi yağı kullanım alanları oldukça fazladır. At kestanesi yağının gıdalarla birlikte alınımı konusunda hekime danışılmalıdır.")
        yaglar.append(atkestanesi)

        let aynisefa = Yaglar(Adi: "Aynısefa (Kalendula) Yağı", Resim: UIImage(named: "aynisefayagi")!, Faydalari: "Cilt bakımında yüksek nemlendirici olarak kullanılır.Hassas ciltleri dengeleyici, ve güçlendiricidir.Tahriş olan ciltleri onarıcı etkiye sahiptir.Güneş ışınlarına karşı koruyucu ve nemlendiricidir.Varis, egzema, sivilce, mantar, pişik, isilik ve döküntü gibi cilt problemlerinde destekleyici ve yardımcıdır.Cilt lekeleri ile savaşır.Vücut çatlakları için özellikle topuk ve dirsek çatlaklarına çok faydalıdır.", KullanimSekli: "Aynısefa yağı cilt üzerine haricen uygulanabilir. Temiz olan cilt üzerine masaj yaparak bir miktar sürülebilir. Aynı zamanda yüz ve göz çevresi için de rahatlıkla kullanılabilir. Saç diplerine ve saç boyuna sürülerek bir süre bekletilir ve saçtan iyice arınması sağlanır. İstenildiği takdirde cilt için kullanılan losyon veya kremlere karıştırılarak da kullanılabilir. Genital bölgelerde meydana gelen mantar iççin genital bölgede haricen kullanılabilir. Aynı zamanda şampuan içine eklenerek de kullanılabilir.")
        yaglar.append(aynisefa)

        let bergamotyagi = Yaglar(Adi: "Bergamot Yağı", Resim: UIImage(named: "bergamotyagi")!, Faydalari: "Hücreleri yenileyerek yaşlanmayı geciktirir. Antioksidanları serbest radikallerle savaşır. Yapılan araştırmalar sonucunda düzenli tüketiminin yüksek şeker hastalığında tedavi edici etkisi olduğu tespit edilmiştir.Bergamot yağı yatıştırıcı bir etkiye sahiptir. Çok fazla flavonoid içerir. Kaygı ve stresi azaltır. Zihni yatıştırır ve beynin kimyasını dengeler. Serotonin ve dopamin salgılanmasını düzenler.Sindirim sisteminin düzenli çalışmasına yardımcı olur. Burada ortaya çıkabilecek enfeksiyon ve hastalıkları önler. İltihabı giderir ve faydalı bakterilerin bağırsakta çoğalmasını sağlar.Kas veya kemik ağrısı olan kişiler bergamot yağı ile ağrıyı hafifletebilir. Antiseptik özelliklere sahip olan bergamot yağı kullanılarak kronik ağrı da önlenebilir.Sedef hastalığı ve egzama gibi cilt hastalıklarını ortadan kaldırır. Cilde rahatlama sağlar. Üstelik cilt lekelerini önlemede etkilidir. Cildi yenileyip canlandırabilir ve yaşlanmayı geciktirebilir.Derideki yaraların hızlı iyileşmesini etkiler. Rahatlatıcı etkisi nedeniyle kas kasılmaları ve krampları için de kullanılabilir.Saç derisinin sağlığını korumak ve oluşan mantarları yok etmek için kullanılabilir. Bunun için şampuanın içine birkaç damla yeterlidir.", KullanimSekli: "Bergamot esansiyel yağı doğrudan cilde uygulanmamalıdır. Vücut losyonu ve masaj için hindistancevizi yağı veya mineral yağ gibi taşıyıcı yağlarla karıştırılabilir.Bu şifalı yağı sabah tok karnına bir bardak su koyarak içebilir ya da dışarıya masaj yaparak uygulayabilirsiniz. Bergamot yağının ruh sağlığından yararlanmak istiyorsanız bu uçucu yağı koklamak kendinizi iyi hissetmenizi sağlayacaktır.")
        yaglar.append(bergamotyagi)

        let biberiyeyagi = Yaglar(Adi: "Biberiye Yağı", Resim: UIImage(named: "biberiyeyagi")!, Faydalari: "Kan dolaşımını hızlandırır.Sinirleri uyarır ve güçlendirir.Mide ve bağırsakları uyararak sindirime (özellikle yağlı yiyecek yendiğinde) yardımcı olur.Mide gazlarını giderir.Safra salgılarını artırır.İdrar söktürürcüdür.Balgam söktürürcüdür.Kas ve eklem ağrılarını dindirir.Mikroplara karşı etkilidir.Antibakteriyeldir.Kansere karşı koruyucudur. Kalp ve damar sağlığının korunmasına yardımcıdır.Tansiyon ve kolesterolü dengeler.Gribe karşı korur.Enfeksiyon ve iltihaplara karşı etkilidir.Öksürüğü keser.Sinir sistemini uyarır.İştahı baskılayarak kilo vermeye yardımcı olur.Karaciğer enzimlerini düzenler.Romatizma ağrılarını dindirir.Bronşit ve sinüzitte tedavi edicidir. Vücudu arındırır.Saç dökülmesini önler.Hafızayı güçlendirir.Karın ağrısına iyi gelir.Cilt hücrelerini yeniler.Selülit oluşumunu engeller, var olanları giderir.Uykusuzluğa iyi gelir.Halsizliğe karşı etkilidir.", KullanimSekli: "Biberiye yağının kullanımı için; Bir pamuk yardımı ile biberiye yağını yüzünüze sürerek ve haricen cildinize masaj yaparak uygulayabilirsiniz. Aynı zamanda; saç bakım ürünler, nemlendirici krem yahut şampuanın içerisine birkaç damla biberiye yağı ilave ederek de kolaylıkla kullanabilirsiniz.Biberiye yağı esansiyel bir yağ olmasından dolayı yağı solumak da kişinin kendisini daha iyi hissetmesine önemli fayda sağlayacaktır. Biberiye yağı ayrıca günde bir defa bir su bardağı suyun içene birkaç damla damlatılarak içilebilir.Eğer herhangi bir kronik sağlık sorununuz bulunuyorsa yahut düzenli olarak ilaç kullanmanız söz konusuysa, biberiye yağının kullanmadan önce mutlaka uzman bir doktorun görüşünü almanızda çok büyük fayda olacaktır.")
        yaglar.append(biberiyeyagi)

        let cevizyagi = Yaglar(Adi: "Ceviz Yağı", Resim: UIImage(named: "cevizyagi")!, Faydalari: "B1, B2, B6 ve C vitaminlerini bünyesinde bulundurur.Güçlü bir antioksidandır.İçerisinde bol miktarda protein, lif, omega 3 ve 6 yağ asitleri bulunur.Kalsiyum, çinko, magnezyum, fosfor, bakır, selenyum, demir ve manganez minerallerini barındıran nadide yemişlerdendir.Kalp ve damar sağlığını korur.Antidepresan etkisi yüksektir, stresle mücadelede önemli rol üstlenir.Yüksek kolesterolü düşürür.Saçı güçlendirir, geç beyazlama sağlar, kırışıklık gidermede yardımcıdır.Doğal E vitamini kaynağıdır. Bu vitamin hücrelerimizin yenilenmesinden sorumludur.Egzama, sedef ve mantar enfeksiyonu gibi cilt sorunlarında kullanılır.İçerdiği proteinler ile saç derisinde bulunan bakterileri ve ölü hücreleri yok ederek saçı nemlendirir ve saç dökülmesini azaltır.Ceviz yağı saç köklerini güçlendirerek sağlıklı saçlara sahip olmanızı sağlar.Saça parlaklık ve canlılık kazandırır.Kepek sorununa karşı da etkili bir bitkisel yağdır.Ceviz yağı kullanımı sonucunda saçınızın hızlı uzadığını görebilirsiniz. Bir çok kişi ceviz yağını saç uzatma özelliğinden dolayı kullanmaktadır.", KullanimSekli: "Isıtılmadan kullanılması gereken bir yağdır. Ceviz yağı ister içilerek ister de vücuda sürülerek kullanılabilir. Yemek soslarında, salatalarda kullanılan ve masaj yapmak içinde kullanılan bir yağdır. Salatalarda kullanılmak istenmez ise bir tatlı kaşığı kadar içilebilir. Tadı beğenilmediği takdirde bir bardak su içerisine ceviz yağından üç damla kadar eklenmesi ile içilerek tüketilebilir.")
        yaglar.append(cevizyagi)

        let camterebentin = Yaglar(Adi: "Çam Terebentin Yağı", Resim: UIImage(named: "camterebentinyagi")!, Faydalari: "Saç dökülmelerine karşı koruma sağlar. Saç köklerini besler, onarır.Saçların hızlı bir şekilde uzamasını sağlar.Saç bakımı yapar, saçlara canlılık verir.Saçtaki kepekleri yok eder.Metabolizmayı hızlandırır.Bağırsaklara fayda sağlar.Romatizma, eklem ağrısı ve kas sertliğine iyi gelir.Banyo suyuna ilave edildiğinde vücudu rahatlatır.İdrar yolu enfeksiyonlarını rahatlatır.Akciğer hastalıkları ile birlikte gelen göğüs ağrılarını azaltmak için kaynar suya damlatılarak buharı solunabilir.Hemoroide iyi gelir.Enerji verir. Stresi ve yorgunluğu giderir.Konsantrasyon eksikliği olan kişiler için de oldukça yararlı bir yağdır.Göz sağlığına fayda sağlar.Balgam söktürücü özelliği vardır. Solunum yollarına iyi gelir.Emzirme döneminde süt arttırıcı özelliği vardır.", KullanimSekli:"Çam terebentin güçlü bir antibiyotik ve antiseptik özelliği bulunan yağ, ağrı kesici ve idrar sökücü özellikleri ile de tercih edilmektedir.Çam ağaçlarının üzerinde kendiliğinden oluşan çam terebentin ayıca çam ağacı kesildiğinde de elde edilebilir. Çam terebentin yağı cilde uygulanacaksa başka bir yağ ile seyreltilmelidir.Solunum yollarını rahatlatmak için kullanılacaksa sıcak suya birkaç damla atılarak buharı solunabilir.Leke ve sivilcelerinizi yok etmek amacıyla çam terebentin sabunu kullanabilirsiniz. Bu sabunla her sabah yüzünüzü temizleyerek güne başlamak sağlıklı bir adım olacaktır. Cilt hücrelerinizi yenileyecek ve canlılık kazandıracaktır.Stres ve yorgunlukla başa çıkmak istediğinizde, dilerseniz banyo suyunuza bir iki damla çam terebentin yağı ilave edebilirsiniz. Bulunduğunuz ortama yayılarak sizi daha iyi hissettirecektir.Çam terebentin yağını şampuan içine ekleyerek çam terebentin şampuanı elde edebilirsiniz. Her duş esnasında saçlarınıza bakım yapmanız daha sağlıklı olacaktır. Bunun için bir şişe şampuan içine yaklaşık 20 damla çam terebentin yağı eklemeniz yeterli olabilir. Yalnız unutmamak gerekir ki; bir süre sonra yağ şampuan üzerine çıkacaktır. Bu nedenle her kullanımda şampuan şişenizi çalkalamalısınız.")
        yaglar.append(camterebentin)

        let corekotuyagi = Yaglar(Adi: "Çörek Otu Yağı", Resim: UIImage(named: "corekotuyagi")!, Faydalari: "Antienflamatuar ve antioksidan özelliklere sahiptir.İltihapların tedavisinde kullanılır.Kilo verme sürecine destek olur.Saç dökülmelerini azaltır. Saç çıkartır.Bronşları temizler ve öksürüğe iyi gelir.Romatizmaya ve eklem ağrılarına iyi gelir.Kabızlığı giderir. Hemoroid için iyileştirici etkisi vardır.Kan akışını hızlandırır, kalp sağlığını korur.Cildin nem dengesini sağlayarak kurumasını önler.Cinsel gücü arttırıcı bir etkisi vardır.Çatlakların azalmasında etkilidir.Kaşıntılı ve ağrılı olabilen sedef hastalığının semptomlarını azaltır.", KullanimSekli: "Çörek otu yağı soğuk sıkım olarak kullanılmalıdır. Pişirilmeye uygun bir yağ değildir. O yüzden salata ve yemeklere sonradan eklenmelidir.Çörek otu yağı tek başına da günde 1 çay kaşığı tüketilebilir.  Her ne kadar doğal bir ürün olsa da çok fazla ve uzun süreli kullanımı durumda yan etkiler oluşabilmektedir. Bu nedenle kullanmadan önce uzman bir hekime danışılması gerekmektedir.Çörek otu yağını harici olarak cilde de uygulanabilir. Bu şekilde kullanıldığında Hindistan cevizi veya badem yağında seyreltilmelidir. Antibakteriyel ve antienflamatuar özelliklerinden dolayı bu karışım akne veya egzama gibi yaygın cilt problemlerinde kullanılabilir.")
        yaglar.append(corekotuyagi)

        let defneyagi = Yaglar(Adi: "Defne Yağı", Resim: UIImage(named: "defneyagi")!, Faydalari: "Defne yağı, romatizmaya iyi gelen bir yağdır. Romatizma hastalıklarından kurtulmak için ağrıyan bölgenin üzerine defne yağı sürerek masaj yapmanız gerekir. Romatizması olan kişilerin dayanılmaz ağrılarını hafifletmeye yardımcı olur.Vücutta bulunan zararlı toksinlerin dışarı atılmasına defne yağı, yardımcı olur. Düzenli kullanıma bağlı olarak kısa süre içinde defne yağı vücuttaki zararlı toksinlerin dışarı atılmasını sağlar.Defne yağı, bağışıklık sistemini güçlendirmeye ve vücudun hastalıklara karşı direncini arttırmaya yardımcı olur. Defne yağını düzenli kullanan bir kişi, kendisini daha iyi hisseder. Bağışıklık sisteminin ihtiyacı olan tüm enzimleri salgılayan defne yağı, çok etkili bir bitkisel yağdır.Defne yağı, hem saça hem de cilde iyi gelmesi ile bilinen çok etkili bir bitkisel yağdır. Doğal yollarla saç ve cilt bakımı yapmak isteyenler defne yağını kullanır. Saçınıza ve cildinizin belirli bölgelerine sürdüğünüz yağ ile saçlarınızın daha parlak ve cildinizin daha canlı görünmesini sağlayabilirsiniz.Defne yağının antioksidan özelliği vardır. Tonik olarak kullanılır ve vücudu temizleyici bir özelliği vardır.Aşırı terlemeyi azaltır ve ter kokusunu önler.", KullanimSekli: "Defne yağı, onarılmak istenen bölgeye sürülerek kullanılır. Saç bakımı için defne yağı kullanmak isteyenlerin ise, defne yağını saça sürerek uygulaması gerekir. Defne yağı, zeytinyağlı yiyeceklere 1 tatlı kaşığını geçmeyecek şekilde dökülerek de kullanılabilir.")
        yaglar.append(defneyagi)

        let feslegenyagi = Yaglar(Adi: "Fesleğen Yağı", Resim: UIImage(named: "feslegenyagi")!, Faydalari: "Bakterilerle savaşmaktadır.Enfeksiyonlara karşı mücadele etmektedir.Hastalığa neden olan iltihabı önemli ölçüde azaltmaktadır.Virüslerle mücadele etmektedir.Solunum kanallarında meydana gelen tıkanıklığı gidermektedir.Ödem atmayı kolaylaştırmaktadır.Serbest radikal hasarıyla mücadele etmektedir.Sinir sistemini uyarmaktadır.Adrenal korteksin uyarılmasını sağlamaktadır", KullanimSekli: "Fesleğen, taze çiçekli dalları ve tohumları ile uçucu yağ taşır. Bu yağın içeriğinde estragol, linalol, cineol ve pinene rastlanır.Dahilen kullanılacaksa, günde bir kez 2-3 damla halinde çaylara cilt bakımı karışımlarına, çeşitli kürlere ve yemeklere katılabilir.Harici kullanımındaki en önemli nokta, tüm uçucu yağlarda da bilindiği üzere, fesleğen yağının da saf halde kullanılmasının faydalı olmak yerine zararlı olacağıdır. Bu sebeple, eğer haricen uygulanacaksa jojoba yağı, avokado yağı, susam yağı gibi taşıyıcı yağlar ile karıştırılarak kullanılmalıdır. Uçucu yağlar suda çözünmezler. Bu sebeple, eğer banyo suyuna karıştırılmak istenirse önce süt, karbonat, deniz tuzu ya da taşıyıcı yağlarla çözündürülmelidir.")
        yaglar.append(feslegenyagi)

        let gulyagi = Yaglar(Adi: "Gül Yağı", Resim: UIImage(named: "gulyagi")!, Faydalari: "Cildi kirden, yağdan arındırır.Ciltte oluşan güneş ve gebelik lekelerinin görünümünü hafifletir.Gözlerinizde kanlanma veya göz nezlesi gibi sorunlarda gül yağına batırılmış pamukla göz kapağına kompres yapmak işe yarayabiliyor.Doğal makyaj temizleyicisi olarak kullanabilirsiniz.Cildi canlandırır, gençlik kazandırır.Gül yağı ile karın bölgesine masaj yapılırsa kabızlık sorunu hafifler.Alerjik cilt sorunları, egzama ve açık yaralarda tedavi edici rolü vardır.Bir bardak suya 1 tatlı kaşığı gül yağı katarak gargara yapmak, ağız içinde oluşan bakterileri yok eder, ağız kokusunu önler.Antiseptik özelliğinden dolayı mikropları öldürmekte etkilidir.Ciltte her hangi bir sebeple oluşan kızarıklıkları hafifletir.Nefes darlığı, astım, kronik öksürük gibi sorunları azaltır.Kas ağrıları, burkulma, ödem gibi sorunlarda gül yağı ile masaj ya da kompres önerilir.Gül yağı ile masaj yapıldığında sindirim sisteminin fonksiyonları hızlanır.Stresli, depresif durumlarda gül yağı katılmış su ile duş alınması, küvetin doldurulduğu suya gül yağı katılması önerilir.Gül yağının huzur verici, rahatlatıcı bir etkisi vardır. Bu sebeple baş ağrısı yaşanan ya da stres altında hissedilen anlarda bileklere, şakaklara gül yağı ile masaj yapılması iyi gelebilir. Bulunduğunuz ortamda cam bir kasenin içine su doldurup birkaç damla da gül yağı koymak sizi rahatlatacaktır.", KullanimSekli: "Gül yağı kullanımında miktarı fazla kaçırmamak sağlık açısından önemlidir. Gül yağı, cilde masaj yapılarak uygulanmaktadır. Bununla birlikte gül yağının cilde uygulanmasından önce birkaç damla badem yağı gibi taşıyıcı yağlarla seyreltilmesi önerilmektedir. Gül yağının kullanımına ilişkin akla takılan sorulardan biri de içilip içilemeyeceği hususu. Gül yağı, sabah ya da akşam olmak üzere bir bardak suyun içerisine 2-3 damla eklenerek içilebilmektedir.")
        yaglar.append(gulyagi)
        
        let hardalyagi = Yaglar(Adi: "Hardal Yağı", Resim: UIImage(named: "hardalyagi")!, Faydalari: "Kireçlenmelere ve romatizmaya faydalıdır.Hardal yağı, iştah açıcı ve hazmı kolaylaştırıcı etkiye sahiptir.Akciğer zarı iltihabının tedavisinde kullanılır.Göğsü yumuşatıcı etkisi vardır.Öksürüğü keser.İç organlarda biriken kanı dışarıya atarAğrı kesici etkisi bulunmaktadır.Hardal yağı vücutta antioksidan görevi gördüğünden saçların kuvvetlenmesine yardımcı olur.Cildi dış etkenlerden korur ve cilt hücrelerini yeniler.Cilt çatlaklarını giderir ve cilde bakım yapar.Kilo problemi olanlara kilo vermelerinde yardımcı olur.Kasları gevşetici ve rahatlatıcı özelliği vardır.Yapılacak masaj ile baş ağrılarının giderilmesine yardımcı olur.Kaşıntı olan bölgelere sürüldüğü zaman kaşıntı problemini giderir.Zeytinyağı ile karıştırılıp cilde sürüldüğü zaman selüloit ve çatlaklıkları yok eder.", KullanimSekli: "Hardal yağını çok az miktarda salata soslarına ekleyerek salata gibi yiyeceklerinize tatlı acı bir aroma verebilirsiniz. Mümkün olduğunca 1 ya da 2 damla fazlasını kullanmamalısınız.Farklı bir bitkisel yağla beraber kullanılması önerilen hardal yağı, cilt maskelerinde yer almaktadır. Cilt maskesi için kullanılan hardal yağı ölü hücrelerin atılmasını ve hücre yenilenmesini gerçekleştirir.Saç ve cildi onarması amacıyla, Hindistan cevizi yağı ya da badem yağı ile bir karışım hazırlayıp uygulayabilirsiniz.Hardal yağını kuru ciltlere nemlendirici olarak sürmek istediğinizde, bir miktar suyla açmanız önerilir. Açık yara ve kesiklere doğrudan sürülmesi önerilmez.Hardal yağı saç maskesi için tercih edilecekse saçlarda 30 dakikadan fazla kalmamalıdır.")
        yaglar.append(hardalyagi)
        
        let hintyagi = Yaglar(Adi: "Hint Yağı", Resim: UIImage(named: "hintyagi")!, Faydalari: "Saçların hızlı uzamasını, gürleşmesini ve gürleşmesini sağlar.Saç kıran ve kepeği önler.Kabızlığa karşı etkilidir.Kaş ve kirpiklerin gürleşmesini sağlar.Eklem ağrılarını kısa sürede geçirir.Sivilce ve yara izlerini kapatır.Cilt kesikleri ve yanıklara karşı etkilidir.Yaşlanma karşıtı etkisiyle kırışıklıkları azaltır.Vücut çatlaklarına karşı etkilidir.Tırnakları güçlendirir, kırılmasını önler ve uzatır.", KullanimSekli: "Hint yağından 3 gün boyunca bir kaşık kullanmak kabızlığı gidermeye yardımcın olabilir. hint yağı geçmişten günümüze etkili bir kabızlık ilacı olarak bilinmektedir.Eklem ağrılarının oluştuğu bölgeye belirli bir miktar hint yağı sürerek ağrıları kısa süre içerisinde azaltabilirsiniz.Haftada iyi defa kulak çubuğuna damlatıp kaşınıza sürdüğünüz Hint yağı, kaşlarınızın gürleşmesini sağlar. Hint yağını saç diplerine masaj yaparak uyguladığınızda kan dolaşımını hızlandırarak saçlarınızın daha hızlı uzamasını sağlayabilirsiniz.İçerisinde yer alan omega 3 yağ asitleri cildinizi derinlemesine nemlendirir ve gerginleşmesini sağlar. Cildinizi derinlemesine nemlendirmek istiyorsanız çatlak olan bölgelere duştan sonra masaj yaparak Hint yağını uygulayabilirsiniz.")
        yaglar.append(hintyagi)
        
        let hindistancevizi = Yaglar(Adi: "Hindistan Cevizi Yağı", Resim: UIImage(named: "hindistanceviziyagi")!, Faydalari: "Besin değerleri açısından oldukça zengindir.Antioksidanlar ile doludur.Böbrek sağlığını korumasıyla bilinir.İdrar yolu enfeksiyonlarına karşı etkilidir.Parazit oluşumunu önler.Kalp ve damar sağlığını korur.Hormonları düzenler.Kronik yorgunluğa karşı etkilidir.Kusmaya ve gaz problemlerine iyi gelir.Vücuda enerji verir, kan şekerini dengeler.İştahı kestiği için zayıflama amacıyla kullanılır.Cilt ve saç sağlığını korur, saçların sağlıklı uzamasını destekler.Beyin fonksiyonlarının iyileşmesine destek olur.Sindirimi kolaylaştırır.Bağışıklığı güçlendirir, vücut direncini arttırır.Beslenme düzenine eklemek oldukça kolaydır.", KullanimSekli: "Hindistan cevizi yağı kullanım sürecinde özel hazırlık gerektirmez. Doğrudan kavanozdan alınıp yemek tariflerine eklenebilir. Hindistan cevizi yağı, katı dokusu nedeniyle nadiren salata yağı olarak kullanılır ve bu nedenle pişirme işlemlerinde daha yaygın olarak kullanılır.Toz formda olan hindistan cevizi ürünleri uzun raf ömrü ile mutfakların vazgeçilmezidir. Ortamın nemine, sıcaklığına göre değişen bozulma süreleri olmakla beraber ürünün kokusundan kolayca anlaşılan bir durumdur.Saçlarınızın parlaklığını artırmak ve zarar görmesini önlemek için saçlarınıza hindistan cevizi yağı uygulayabilirsiniz. Bu yağ, saç derisine mineral yağlardan daha iyi nüfuz edebilir.Terin kendisinin kokusu olmasa da, cildinizde yaşayan bakteriler istenmeyen kokular üretebilir. Hindistan cevizi yağının güçlü antibakteriyel özellikleri, onu kimyasal içermeyen harika bir doğal deodorant yapar. Ayrıca bacaklarınız, kollarınız ve dirsekleriniz için harika bir nemlendiricidir.Yapılan çalışmalar, hindistan cevizi yağının çürüklere karşı koruma sağladığını, diş eti iltihabını iyileştirdiğini ve oral bakteri dengesini etkilediğini bulmuştur")
        yaglar.append(hindistancevizi)
        
        let isirganotu = Yaglar(Adi: "Isırgan Otu Yağı", Resim:UIImage(named: "isirganotuyagi")! , Faydalari: "Isırgan otu yağı cilt sorunlarında cilt yenilemek ve lekeleri yok etmek içi faydalı olmaktadır. Isırgan otu yağı cildin temizlenerek zararlı maddelerden arınmasına yardımcı olmaktadır. Isırgan otu yağı özellikle sedef hastalığı gibi hastalıklarda faydalı olmaktadır. Cilt sorunlarında özellikle güneş lekelerinde ve diğer rahatsızlıklarda kullanılması cilde parlak bir görünüm sağlamaktadır. Isırgan otu yağı tırnak ve ayak bakımında da faydalı olmaktadır.Saç bakımında ısırgan otu yağı kullanımı saçların uzaması, saç diplerinin bakımı, saç tellerinin onarılması ve gürleşmesini sağlamakta faydalı olmaktadır. ", KullanimSekli:"Isırgan otu yağı cilt için kullanımında sürülerek veya krem içerisine karıştırılarak kullanılabilen bir yağdır. Isırgan otu yağı cilt için soğutularak kullanıldığında daha iyi temizleyerek arındırmaktadır.Isırgan otu yağı saç bakımı için kullanıldığında diğer faydalı yağlar ile kullanılabildiği gibi şampuan içerisine eklenerek de kullanılmaktadır. Isırgan otu yağı saç bakımında kullanılırken özellikle saçları yıkamadan önce sürülerek beklenebilmektedir.Isırgan otu kullanımında cilt için hafif şekilde kullanılmalıdır. Isırgan otu yağı etkili bir yağ olduğu için kullanımından önce alerjik bünyelere dikkatli bir şekilde kullanılmak gerekmektedir. Isırgan otu yağı faydaları özellikle cilt ve saç için kullanılmasının yanında doğal bir yağ olduğu için kullanılmasında bir yan etki bulunmamaktadır.")
        yaglar.append(isirganotu)
        
        let jojobayagi = Yaglar(Adi: "Jojoba Yağı", Resim: UIImage(named: "jojobayagi")!, Faydalari: "Jojoba yağı, cildi temizler ve makyaj kalıntılarından arındırır.Cildi nemlendirir ve besler.Antialerjen içeriğiyle ciltteki sivilce ve akneleri giderir.Yaşlanma belirtisi olan kırışıklıkları giderir, yenilerinin oluşmasını önler.Cildin yağ dengesini korur.Ciltte yanma, kuruma ve dökülmeyi önler.Cilde esneklik kazandırır.Hamilelikte ve kilo alıp verme dönemlerinde oluşan göbek, kalça, basen, göğüs çatlaklarını önler.Düzenli olarak jojoba yağı ile masaj yapılan bölgelerde selülit oluşumu engellenir.Ayak kremi şeklinde ayaklara sürüldüğünde ayak kokusunu ve terlemesini önler.Saç derisini nemlendirir ve besler. Bu sayede kepek oluşumu engellenir.Saçların daha hızlı uzamasına yardım eder.Yeni saç oluşumunu destekler.Saçların kırılmasını önler.Saça daha canlı ve yumuşak bir görünüm kazandırır.", KullanimSekli:"cildin üzerine ve saça masaj yapılarak uygulanmaktadır. Bir miktar jojoba yağını cilde masaj yaparak yedirmek faydalı olacaktır. Makyaj sonrası cilt temizliği için kullanılabileceği gibi; cildin ferahlaması ve tazelenmesi için de kullanılabilmektedir. Ayrıca kuru ciltler için cildin nemlendirilmesi için tüm vücuda uygulanabilir. Bu arada bazı yağlarla karıştırılabileceği gibi tek başına da oldukça etkili bir nemlendirme sağlayacaktır.Jojoba yağını saçlara uygulama sırasında da saç diplerine masaj yapılarak tatbik edilir. Bir fırça yardımıyla uygulanabileceği gibi parmak uçlarıyla da aşırı olmadan sadece dip kısımlara uygulanmalıdır. Yarım saat bekledikten sonra saçlar yıkanmalıdır. Bazı bakım ürünleri içerisine de jojoba yağından birkaç damla koymak etkisini artırması açısından fayda sağlayacaktır. Jojoba yağı saçların şekillenmesi için de kullanılabilmektedir.")
        yaglar.append(jojobayagi)
        
        let kafuryagi = Yaglar(Adi: "Kafur Yağı", Resim: UIImage(named: "kafuryagi")!, Faydalari: "Kafur eskiden kalp ve kan dolaşımı rahatsızlıklıkları, öksürük, üşütme, bronşit, ve balgama karşı kulanılmıştır. Günümüzde buna ilavetten soğutucu ve iltihapları önleyici özeliğinden dolayı romatizma, kas ağrıları,burkulma, morarma ve ezilmeye karşı haricen merhem formu kullanılmaktadır.Kan dolaşımını Düzenler.Serinletici ve tonik etkisi vardır.Boyun ve sırt ağrıları için oldukça faydalıdır.Stresin giderilmesini sağlar.Kas ağrılarıi tutulmalar, burkulma gibi durumlarda oldukça yarar sağlar.Astım ve bronşitte balgam söktürücü ve frerahlatıcıdır.Sindirim Sistemi Hastalıkları, Bağırsak gazı ve kabızlık için fayda sağlar.Safra taşlarının tedavisinde kullanılır.Aknede, yanıklarda yağlı ciltlerde derideki ülseratif yaralarda kaslardaki gerilimin giderilerek derinin yumuşamasında kullanılmaktadır.Solunum sistemi hastalıklarından akciğer ödeminde etkisinden dolayı öksürük ve soğuk algınlığında pnomonide kullanılmaktadır.", KullanimSekli: "Kas kramplarını , spazmları ve sertliği gidermeye yardımcı olabilir.Kullanmak için günde birkaç kez kafur yağı ile ağrıyan kaslarınıza masaj yapabilirsiniz.Kafur yağının buhar olarak teneffüs edilmesinde solunum yolları rahatsızlıklarınız için kullanabilirsiniz.Yanık yaralarınız için kafur yağınızı yanıklarınızın üstlerine günde 1 kere sürebilirsiniz.")
        yaglar.append(kafuryagi)
        
//        let kabakcekirdegiyagi = Yaglar(Adi: "Kabak Çekirdeği Yağı", Resim: UIImage(named: "kabakcekirdegiyagi")!, Faydalari: "Kabak çekirdeği yağı idrar zorluklarında fayda sağlar.Amino asit barındırdığı için strese ve depresyonda etkilidir.Sabahları sık oluşan mide bulantılarını azaltır.Kemiklerin güçlenmesini sağlar.Kanda oluşan kolesterolün düşmesinde etkilidir.Bağırsakların düzgün çalışmasına yardımcı olur.Kısırlıkta yaşanan hormonal sorunları düzenler.Çocuklarda oluşan bağırsak kurtlarına iyi gelir.Böbrek ve kalbin antioksidan seviyesini arttırır.Mesanede oluşan iltihaplara iyi gelmektedir.Vücudu hastalıklara karşı koruyarak direncini arttırır.Antioksidan etki göstererek vücuttaki serbest radikallerle savaşır.Bağışıklık sistemini güçlendirir.Romatizma hastalıklarında ilaç tedavisini destekleyici olarak kullanılır.Prostat kanserini önler.İdrar kesesi problemlerini en aza indirir.Kalp sağlığını koruyarak kalp krizi riskini azaltır.Daha sık idrara çıkılmasını sağlayarak idrar akışını düzenler.Cildi güzelleştirir.Toksinlerin vücuttan uzaklaştırılabilmesine olanak verir.Güneş lekelerini gidermek için lekeli bölgeye merhem şeklinde sürülür.Bağırsaklarda üreyen kurtların düşürülmesine yardımcı olur.Bağırsakları yumuşatarak kabızlığı önler.Göz çevresine merhem olarak sürüldüğünde yaşlanma belirtilerini en aza indirir.", KullanimSekli: "")
//        yaglar.append(kabakcekirdegiyagi)
        
        let kantoron = Yaglar(Adi: "Kantaron Yağı", Resim: UIImage(named: "kantaronyagi")!, Faydalari: "Sarı kantaron yağı faydaları sayesinde romatizmal rahatsızlıklar, sırt, bel ve adele (kas) ağrıları iyileştirilebilir.Vücutta açılan yaraların ve yanıkların tedavisinde de sarı kantaron yağı kullanılır.Kan dolaşımını sıkılaştırır ve arttırır.Vücuttaki morarmalar için fayda sağlar.Burkulmalara oldukça iyi gelir.Pürüzlü yüz ciltlerinde bakım toniği olarak kullanılabilir.Çıbanlara fayda sağlar, çıbanların kolay geçmesine yardım eder.Yaraların iyileşmesi için kullanılabilecek bir yağdır. Yaralarda mikrop ve iltihap oluşmasını engeller. Aynı zamanda yaralardaki ağrıyı da geçirir.Yara izi, çizik izi gibi vücutta oluşan istenmeyen çiziklerin izlerin geçmesine yardım eder.Vücuttaki hücreleri yeniler, yeni hücre oluşumunu destekler.Güneş yanığı tedavisinde şifalıdır. Güneşten zarar görmüş ciltlerde, cilt lekelerinde kullanılabilen bir yağdır.Sadece yaralarda yada güneş yanığı tedavisinde değil cildinizin güzelleşmesinde de sarı kantaron yağı kullanabilirsiniz. Güzel ve pürüzsüz bir cilde sahip olmak için harika bir yağdır.Kan şekerini düşürücü özelliği vardır.Basur yani hemoroide iyi gelir.Romatizma ve sırt ağrıları gibi çeşitli kemik ağrılarına iyi gelir.Depresyon, umutsuzluk ve kaygılanma gibi ruh hallerine iyi gelir.Oluşan kanamaların kısa sürede dinmesine yardım eder.Varislerin yok edici özelliği vardır.Aynı zamanda yanık tedavilerinde doktorların uyguladığı tedavilerden bir süre sonra bu şifalı yağ kullanılarak yanıklar tedavi edilebilir.Kış aylarında çok üşümekten ve ayaklarınızın bir türlü ısınamamasından yakınıyorsanız bu şifalı yağı kullanabilirsiniz. Bu yağı topuklarınıza sürebilirsiniz. Bu sayede kışın ayaklarınızın üşümediğini fark edeceksiniz.", KullanimSekli: "Kantaron yağı, sıklıkla cilde sürülerek kullanılan bir yağdır. Yanık veya yaraların tedavisinde sorun yaşanan bölgeye birkaç damla damlatıldıktan sonra masaj yapılarak kullanılmaktadır. Bakım amacı ile kullanıldığı zaman güneşe çıkılmayacak zamanlarda cilde birkaç damla olarak damlatılır ve akabinde masaj ile cilde sürülür. Gece yatmadan önce cilde sürülmesi önerilen kullanım şekilleri arasındadır. Kişilerin kantaron yağını uygulamadan önce bileklerine birkaç damla damlatarak alerjik bir reaksiyonun olup olmadığını gözlemlemeleri doğru olacaktır.Kantaron yağı, kantaron çayı yapımında eklenerek de tüketilebilmektedir. Bir çay kaşığı olarak direkt içilmesi de bazı durumlarda önerilebilmektedir. Kantaron yağı sıcak suya birkaç damla damlatılarak elde edilebilmektedir. Kantaron bitkisi ile kantaron çayı yapmak için ise içme suyu kaynatılır. Sonra camdan bir demliğe dökülür. İçerisine birkaç adet kantaron bitkisi atılarak yaklaşık olarak on dakika kadar bekletilir. Süzdükten sonra içime hazır hale gelir.")
        yaglar.append(kantoron)
        
        let kamelya = Yaglar(Adi: "Kamelya Yağı", Resim: UIImage(named: "kamelyayagi")!, Faydalari: "Daha güzel ve yumuşak bir cilde sahip olmanızı sağlar.Saçınızdaki kırıkları onarıp saçınıza daha yumuşak ve parlak bir görünüm verir.Kamelya Yağı kepek oluşumunu da önler.Ciltteki çatlakları giderir gözaltı morluklarının üstesinden gelir.Çatlamış dudaklarınıza uygularsanız dudaklarınıza nem katar ve daha parlak bir görünüm verir.", KullanimSekli: "Bir miktar kamelya yağını tavada hafif şekilde ısıtın. Ardından parmak uçlarınızla 5-10 dakika saç derisine masaj yapın. Streç film ya da bone ile yarım saat kadar saçınızda bekletin. Güzelce temizleyin. Haftada bir kere uygulayabilirsiniz. Bu kür sayesinde; saçlarınız yumuşar, kepekler giderilir, saç kırılması engellenir. Saç köklerine gerekli oksijenin ulaşmasını sağlayarak saçların uzamasına yardımcı olur.Bu yağ cilt üzerinde oldukça etkilidir. Öncelikle makyaj temizleyici olarak kullanabilirsiniz. Bunun için bir miktar kamelya yağını pamuğa dökerek makyajınızı silin. Göz makyajınızı bu yağla temizlerken aynı zamanda kaş ve kirpiklerinize de bakım yapmış olursunuz.Cildi nemlendirmek ve çatlakları engellemek için ise aynı oranlarda çay yağını karıştırarak her gün nemlendirme rutininize ekleyebilirsiniz.")
        yaglar.append(kamelya)
        
//        let karabasyagi = Yaglar(Adi: "Karabaş Otu Yağı", Resim: UIImage(named: "karabasyagi")!, Faydalari: "", KullanimSekli: <#T##String#>)
        
        let karabiberyagi = Yaglar(Adi: "Karabiber Yağı", Resim: UIImage(named: "karabiberyagi")!, Faydalari: "Duygusal ve ruhsal durumu dengeli hale getirmesiyle ünlü olan karabiber yağı, kan dolaşımını rahatlatır ve sinir sistemi sorunları için doğal çözümler sunar. Karabiber yağı vücuda enerji verir, ısıtır. Benzersiz çok yönlülüğü sayesinde duyuları canlandırırken zihinsel netliğin artmasına yardımcı olur. Özellikle sporcular ve aktif hayat tarzına sahip kişiler tarafından kullanımı oldukça yaygın.", KullanimSekli: "Kas ağrılarını azaltmak için ağrıyan bölgeye sürebilirsiniz.Karın bölgenize bir miktar karabiber yağı sürüp birkaç damla da ağızdan alırsanız hazmı kolaylaştırmanıza yardımcı olur,Bir bardak suyun içine birkaç damla karabiber yağı koyarak tansiyonunuzu düşürebilirsiniz.Kireçlenme, gut ve kronik romatizma ağrıları için sorunlu bölgeye uygulayabilirsiniz.Günlük olarak bir bardak suya 2-3 damla karabiber yağı ekleyerek detoks yapabilirsiniz.Göğsünüze karabiber yağı sürerek sıkışma ve daralma hissinden kurtulabilirsiniz.Karabiber yağını koklayarak ya da suya birkaç damla koyarak solunum sıkıntısını giderebilirsiniz.Aynı yöntemi kullanarak sigara içme isteğinizi azaltmak için de karabiber yağını kullanabilirsiniz. Bilimsel araştırmalar karabiber yağının sigarayı bırakmaya çalışanların içme isteğini azalttığını ve kriz anında sinirlerini sakinleştirdiğini ortaya koyuyor.IBS (İrritabl Bağırsak Sendromu), insülin direnci, kaygı ve depresyon, yüksek şeker, beyin ve karaciğer iltihaplarının tedavisinde kullanılabileceğine dair klinik araştırmalar bulunuyor.")
        yaglar.append(karabiberyagi)
        
        let karanfilyagi = Yaglar(Adi: "Karanfil Yağı", Resim: UIImage(named: "karanfilyagi")!, Faydalari: "Karanfil yağı antioksidan bir yağ olduğu için mikroplardan kurtulmaya ve ağrıları dindirmeye faydalı olmaktadır. Karanfil yağı baş ağrılarında kullanıldığı gibi diğer ağrıları hafifletmek için etkili ve faydalıdır. Eklem ağrılarını dindirmekte kullanılmaktadır. Karanfil yağı çocuklarda diş ağrılarını dindirmek için ve diş çıkartırken ağrıları azaltmak için kullanılmaktadır.Karanfil yağı saç diplerinde ve saç bakımında faydalı bir yağdır. Karanfil yağı kokusu yoğun olduğu için strese karşı etkili ve rahatlatıcı olmaktadır. Diş ağrılarında faydalı olduğu kadar ağız içi yaraları ve ağız kokularını yok etmek için faydalıdır. Ağrı kesici özelliği doğal yapıda olduğu için rahatlıkla kullanılmaktadır. ", KullanimSekli: "Karanfil yağı uyku problemlerinde kullanılmak istendiğinde yarım çay bardağı suyun içerisine 2 damla konularak uykudan önce içilmektedir.Bebekler ve çocukların diş ağrıları için 4 damla karanfil yağı 4 damla zeytinyağı karıştırılarak ağrılı dişlere sürülmektedir.Aşırı akne ve sivilce sorunlarında sarımsak ezilerek içerisine karanfil yağı damlatarak oluşturulan solüsyon sürülmelidir.Karanfil yağı özellikle eklem ağrılarında ağrılı bölgeye birkaç damla sürülerek masaj yapılmalıdır. Diş ağrılarında karanfil yağı su ile karıştırılarak gargara yapılabilmektedir. Saç için kullanılan bakım kürlerinde başka yağlarla karıştırılması gerekmektedir. Özellikle badem yağı ile karıştırılarak kullanılması önerilmektedir.Karanfil yağı kullanım alanları arasında kaynar suya damlatılarak buhar haline getirilip oda içerisinde bulunan mikropları yok etmek için kullanılmaktadır. Üst solunum yolları enfeksiyonlarını rahatlatmaktadır. Karanfil yağı kullanımı ağrı kesici ve uyuşturma özelliği olduğundan dolayı dikkatli kullanılması gereken bir yağdır. Karanfil yağı keskin özellikte bir yağ olduğu için alerjik yapılı kişilerin dikkatli şekilde kullanılması önerilmektedir.")
        yaglar.append(karanfilyagi)
        
        let kayisiyagi = Yaglar(Adi: "Kayısı Yağı", Resim: UIImage(named: "kayisiyagi")!, Faydalari: "Bağışıklık sistemini güçlendirir,Egzama ve benzeri hastalıkların etkisini azaltır,Saçı besleyici özelliği vardır,Cildi temizler ve daha canlı olmasını sağlar,Solunum hastalıklarına iyi gelir,Kabızlığa iyi gelir,Kalp rahatsızlığı riskini azaltır,Kolesterolü düşürür,Saç ve yüz bakımına iyi gelir,Ciltte oluşan kırışıklıklara iyi gelir, akne oluşumunu önler.", KullanimSekli: "Kayısı yağı, içerisine bal veya süt eklenerek kullanılabilir. Cilde sürmek için kayısı yağı içerisine 1 yemek kaşığı bal ve süt ekleyebilirsiniz. İyice karıştırdıktan sonra yüzünüze sürüp kurumasını bekleyin. Yaklaşık 20 dakika sonra yüzünüzü yıkayabilirsiniz. Ayrıca içeceklerin içerisine az miktarda kayısı yağı ekleyip, bu şekilde tüketebilirsiniz. Özellikle su ve çay gibi içecekler ile tüketmenizde herhangi bir sakınca yoktur.Kayısı yağını kullanırken aşırıya kaçmamaya çalışın. Yararlı olan bu ürünü düzenli periyotlarda kullanırsanız daha doğru bir kullanım olur. Düzenli ve ölçülü kullanılan kayısı yağı ile daha sağlıklı bir hayat yaşayabilirsiniz.")
        yaglar.append(kayisiyagi)
        
        let kekikyagi = Yaglar(Adi: "Kekik Yağı", Resim: UIImage(named: "kekikyagi")!, Faydalari: "Solunum yolu rahatsızlıklarına, soğuk algınlığına, grip ve nezleye iyi gelmektedir. Alyuvar oluşumunu artırır, kurt düşürücü olarak da bilinmektedir. Gastrit gibi mide rahatsızlıklarına yardımcı olur. Yüksek tansiyon ve kolesterolü dengeleyen bitkisel yağlar arasındadır.", KullanimSekli: "Temiz cilde pamukla sürülerek tonik şeklinde yüze sürülebilir.Bir bardak ılık suyun için 3-5 damla damlatılarak içilebilir.Grip, soğuk algınlığı gibi durumlarda kaynar suya 3-5 damla damlatılıp buharı buruna çekilebilir.Pişmiş yemeklere eklenebilir.Saç diplerine masaj yapılı 15-20 dk. bekletilerek saç bakımı için kullanılabilir.Sprey şeklinde bir kutu içerisi suyla doldurulup, içerisine 15 damla kekik yağı damlatarak, böcek ve haşereler uzaklaştırılabilir.Egzama, sedef, mantar gibi cilt hastalıklarında problemli bölge temiz bir pamuk üzerine kekik yağı damlatılarak silinebilir.")
        yaglar.append(kekikyagi)
        
        let kimyonyagi = Yaglar(Adi: "Kimyon Yağı", Resim:UIImage(named: "kimyonyagi")!, Faydalari: "ştah açar, hazımsızlığı giderir. Mide ve bağırsaklarda gaz birikmesini engeller. Birikmiş gazı söktürür, sinirleri yatıştırır, sinirsel baş dönmesini keser, anne sütünü arttırır, adet kanamalarının düzenli olmasını sağlar, idrar söktürür. Bunların dışında; Yüksek tansiyonu düşürür, bağırsak kurtlarının düşürülmesine yardımcı olur, sivilce ve egzamada kullanılır. Romatizma ve şişmanlıkta faydalıdır. Hamilelikte kullanılmaz.", KullanimSekli: "Kimyon yağı bazen harici olarak insanlarda kızdırıcı etkisi nedeniyle adele ağrılarında ve romatizmal ağrılarda da kullanılmaktadır. Bu yağ başta tatlı badem yağı olmak üzere birçok farklı bitkisel yağla karıştırılarak kullanılabilmektedir. Eğer sizlerde kimyon yağı kullanmak istiyorsanız bu durumlarda tatlı badem yağı yağlara ilave olarak kullanabilirsiniz. Bunun içi 20 Cc badem yağı içerisine 10 damla kimyon yağı ekleyerek bol bol karıştırın. Bu karışım yağı cilde sürerek uygulayabilirsiniz. Eğer bu yağı ağız yoluyla alacaksanız direk olarak kimyon yağını bir salata içerisin ekleyerek tüketin. Eğer isterseniz bir küp şeker üzerine 5-6 damla damlatarak bu şekeri tüketebilirsiniz. Bu şekilde kimyon yağının acı tadını şeker bastırmış olacaktır.")
        yaglar.append(kimyonyagi)
        
        let kiviyagi = Yaglar(Adi: "Kivi Yağı", Resim: UIImage(named: "kiviyagi")!, Faydalari: "Cildi canlandırır,Nemlendirici ve yumuşatıcı özelliği için kullanılır,Bağışıklık sistemini ve vücudu güçlendirici etkisi vardır,Bağırsakları çalıştırır, sindirimi kolaylaştırır ve kabızlığı giderir,Soğuk algınlığı, nezle ve gribe iyi gelir,Astım hastalarına nefes açıcı etkisinden dolayı iyi gelir,Başta göğüs kanseri olmak üzere, kanser oluşumuna ve ilerlemesine karşı koruyucu özelliği bulunur,Tansiyonu düşürür,Kandaki kolesterol oranını düşürür,Kan basıncını dengede tutar,Karaciğeri çalıştırır,Kansızlığa iyi gelir,Kanı temizler,Yaşlılıktan dolayı oluşan belirtileri azaltır.", KullanimSekli:"Cilt nemlendirici, cildi yumuşacık ve canlandırıcı olarak kivi yağı kullanılmaktadır. Bunun için cilde masaj yaparak uygulanabilir. Friksiyon yöntemi ile kullanıldığında deri altındaki doku ve kaslara etki eder. Banyo suyuna tek başına yada aroma terapi yağları ile karıştırılarak kullanılabilir. Astım ve öksürük tedavisinde nefes açıcı özelliğinden yararlanmak mümkündür. Anemi ve mide problemi gibi nedenlerle kullanılırken, Bir çay bardağı suya 3 damla konularak günde 3 defa içilebilir. Bu sayede kivi yağı bağırsakları yumuşatın toksinlerin atılmasına yardımcı olur ve vücudu temizler.")
        yaglar.append(kiviyagi)
        
        let kusburnuyagi = Yaglar(Adi: "Kuşburnu Yağı", Resim: UIImage(named: "kusburnuyagi")!, Faydalari: "Cildin Nem Dengesini Korur.Hücre Yenilenmesini Destekler.Mikropları Temizler.Kırışıklık Oluşumunu Azaltır.Vücut Direncini Yükseltir.Saçları Besler.Cilt Lekelerini ve Yara İzlerini İyileştirir.Ağrı Kesicidir.Enfeksiyonu Temizler.Baştan Ayağa Canlılık Kazandırır.", KullanimSekli: "Parmak uçlarına bir damla alınan kuşburnu yağını göz çevresinden çeneye kadar yedirebilirsiniz. Düzenli uygulamada farkı göreceksiniz.Aromaterapi alanında da tercih edilen kuşburnu yağı banyo suyuna eklenebilir.Saçlara canlılık vermesi amacıyla kullanmak istediğinizde, saç bakım maskesi içine 5 damla kadar ekleyebilirsiniz.Cilt çatlaklarında, kuruma durumlarında nemlendirici krem gibi sürebilirsiniz.Ağrı kesici etkisini görmek isterseniz, eklemlere masaj yaparak uygulayabilirsiniz.")
        yaglar.append(kusburnuyagi)
        
        let lavantayagi = Yaglar(Adi: "Lavanta Yağı", Resim: UIImage(named: "lavantayagi")!, Faydalari: "Yaşlanma karşıtı olarak kullanılabilir. Yaşlanma ile ortaya çıkan kırışıklıkların azaltılmasına fayda sağlar.Yanıkların ve yaraların çabuk iyileşmesine yardım eder.Egzama ve sedef hastalığı gibi cilt hastalıklarına yarar sağlar.Akne ve sivilceleri yok edici etkisi vardır.Saç dökülmesini önler. Erkeklerin saç dökülmesi için de kullanılabilecek bir yağdır.Saçkıran için de kullanılabilecek bir yağdır. Özellikle sedir ağacı yağı, biberiye yağı, lavanta yağı ve kekik yağı karıştırılarak kullanılırsa saçkırana fayda sağlar.Bitlenmeyi engelleyici özelliği de vardır. Lavanta yağının kokusu sayesinde bitler saçtan uzak durur. Yalnız çocuklar için kullanacaksanız öncelikle mutlaka bir doktora danışmalısınız. Erkek çocuklarda aşırı lavanta yağı kullanımının hormonal dengeyi değiştirdiğine dair söylemler vardır.Kepekleri yok eder.Saçların daha çabuk uzamasını sağlar.Alzheimer hastalığının belirtilerini ve gelişmesini azaltıcı etki yaptığı gözlemlenmiştir.Boğaz ağrısına iyi gelir.İyi bir antioksidan kaynağıdır.Kan basıncını düşürür, bu sayede tansiyonu düşürücü etkisi vardır.Sindirim sistemini rahatlatır. Hazımsızlığı önler.Bağışıklık sistemini güçlendirir.", KullanimSekli: "Cildiniz için kullanacaksanız lavanta yağını aynı oranda zeytinyağı ya da badem yağı ile karıştırıp seyrelterek cildinize uygulayabilirsiniz.Saç sağlığınızı desteklemek istiyorsanız lavanta yağını halihazırda kullandığınız saç maskelerinin içine damlatabilir ya da yine yukarıdaki gibi zeytinyağı veya badem yağı ile seyrelterek saç diplerinize sürebilir ve parmaklarınızla yavaş yavaş masaj yaparak yedirebilirsiniz. Bu şekilde 2 saat bekledikten sonra saçlarınızı güzelce yıkayıp durulamayı da unutmayın tabii.Stresle mücadele konusunda ondan destek almak istiyorsanız bir sprey şişesinin içine su ve 10 damla kadar lavanta yağını aktarıp çalkalayabilir ve yaşam alanınıza (yastıklara, kıyafetlere) bu sıvıyı tıpkı bir oda parfümü gibi püskürtebilirsiniz.Yüksek tansiyonu dengelemek amacıyla lavanta yağından destek almak istiyorsanız lavanta yağını doğrudan koklayabilir ya da bir peçeteye sprey şişeden püskürterek bir süre yakınınızda tutabilirsiniz.Sivrisinekleri evinizden uzak tutmak istiyorsanız sprey şişesinin içinde suyla karıştırdığınız lavanta yağını odalarınıza, perdelerinize, hatta dolaplarınıza sıkabilirsiniz.Soğuk algınlığı durumunda ondan destek almak istiyorsanız büyük bir kase sıcak suyun içine birkaç damla lavanta yağı döküp kısa bir buhar banyosu yapabilir, boğaz ve sırt bölgenizdeki ağrıları azaltmak içinse lavanta yağını zeytinyağı ya da badem yağı ile karıştırıp masaj yaparak boğaz ve sırt bölgenize sürebilirsiniz.")
        yaglar.append(lavantayagi)

        let limonyagi = Yaglar(Adi: "Limon Yağı", Resim: UIImage(named: "limonyagi")!, Faydalari: "Soğuk algınlığı, grip ve nezle sorunlarını ortadan kaldırır. Hafızanın güçlenmesinde faydalıdır, kasların kuvvetlenmesine yardımcı olur. Cilt üzerinde  faydalıdır. Vücutta ki yağların yakılmasında destek sağlar. Kalp damar tıkanıklığını önlemektedi", KullanimSekli: "Öksürük gibi üst solunum yolu iltihabı belirtileri olan kişiler günün bazı saatlerinde limon yağını koklayabilirler. Ayrıca yoğun öksürük durumlarında göğüs kısmına ürünle masaj yapılabilir. Ancak kullanılmadan önce yağın  uygun bir tasyıcı yağla seyreltilmesi gereklidir. Tırnak mantarı ve kırılması gibi durumların önüne geçebilmek için günde birkaç damla limon yağı damlatılabilir. Tansiyon problemlerine karşın bir bardak suyun içerisine birkaç damla limon yağı koyarak istenilen denge sağlanabilir. Diş taşı ve tartarların yol açtığı kötü görünümün giderilmesi için haftada bir gün diş fırçasına bir damla limon yağı eklenebilir. Bu sayede hem ağızda ferah bir his oluşur hem de renk tonlarında açılma meydana gelir.Böcek ısırması ve arı sokması gibi durumlarda antibiyotik görevi görür. Kısa süre içerisinde yaraların iyileşmesini sağlar. Üstelik olası enfeksiyon kapma durumlarının da önüne geçilmesine olanak tanır. Burun kanaması sırasında bir pamuk üzerine birkaç damla yağdan damlatıp delik kısmına nazikçe yerleştirilir. Kanın pıhtılaşmasında etkili olan limon yağı kısa sürede kanamayı durdurur. Ancak hafif şiddetli kanamalarda bu yöntem etkilidir. Çok miktarlı kanamalar için doktora başvurmanız önerilir.")
        yaglar.append(limonyagi)
        
        let mavianemon = Yaglar(Adi: "Mavi Anemon Çiçeği Yağı", Resim: UIImage(named: "anemoncicegi")!, Faydalari: "Güneşten dolayı ciltte oluşum göstermekte olan zararlı etkilerin giderilmesini sağlar.Oluşmakta olan akne ve sivilce izlerini, siyah lekelerin giderilmesini sağlar.Bayanların doğumdan sonra göbek bölgesinde oluşmakta olan doğum lekelerinin yok edilmesinde kullanılır.Kırışıklıkların giderilmesinde ve cildin pürüzünün giderilmesinde faydalı olmaktadır.Cildin nemlilik oluşturmasını ve su dengesini sağlar.Cilde parlaklık kazandırır.Bu yağın kullanımı ile hücrelerin yenilenmesi sağlanır.Vücuda uygulanması ile vücuttaki kas bölgesi güçlenir.Selülitlerin giderilmesi için yağlı bölgelere uygulanır ve bu yağın inceltici bir özelliği vardır.", KullanimSekli: "Mavi anemon çiçeği yağı bir pamuk yardımıyla doğrudan yüze veya cilde sürülebilir.Cilde uygulandığında hafif bir yanma hissine neden olabilir. Eğer ciddi bir kızarıklık veya tahriş yaparsa alerji ihtimalini düşünerek kullanımı sonlandırmalısınız.Bu yağın sizde alerjik bir reaksiyona sebep olup olmadığını anlamak için önce vücudunuzun küçük bir alanında test edebilirsiniz. Eğer cildiniz herhangi bir alerjik tepki göstermezse daha geniş bir alana veya yüzünüze uygulayabilirsiniz.Mavi anemon çiçeği yağını saça doğrudan uygulayabilir veya birkaç damla yağı kullandığınız şampuanın içine ilave edebilirsiniz.Üst solunum yolu hastalıkları için bu yağı sıcak suya ilave edip buharını soluyabilirsiniz.")
        yaglar.append(mavianemon)
        
        let melisayagi = Yaglar(Adi: "Melisa Yağı", Resim: UIImage(named: "melisayagi")!, Faydalari: "Mide ülserine karşı faydalıdır ayrıca gaz giderici özelliğiyle mideyi rahatlatır.Cilt bakımında kullanılabilir. cildi canlandırır ve güzelleştirir.Antiseptik etkilere sahiptir.Soğuk algınlığına iyi gelir. Terletici özelliği vardır.Kas ağrılarında faydalıdır.Baş ağrısı ve migrende kullanılır.Kan temizleyici özelliği vardır.Melisa yağı yorgunluk, uykusuzluk, astım ve nefes darlığı şikayetlerine karşı faydalıdır.Hassas ciltlerde, yüz, vücut masajında ve dudak bakımında kullanılabilir.Hıçkırığa karşı kullanılır.Hafızayı güçlendirir .unutkanlığa iyi gelir.Strese karşı faydalıdır.", KullanimSekli: "Melisa yağı daha çok haricen kullanılır. Suyla seyreltilerek ya da başka bir baz yağ ile karıştırılarak cilde masaj yapılarak sürülebilir. Seyreltilmeden direkt olarak kullanılması çok fazla tavsiye edilmez. Özellikle endüstriyel olarak üretilmiş bitkisel yağların tenle direkt olarak temas etmemesi daha doğru olur. Fesleğen, badem, bergamot, zencefil, lavanta, papatya, gül, ylang-ylang ve biberiye yağları ile gayet ahenkli bir karışım oluşturabilir.Vücut losyonları ile kremlere de katılarak kullanımı söz konusudur.Banyo suyuna katılarak rahatlatıcı etkisinden faydalanılabilir.Melisa yağının zihinsel ve ruhsal faydaları da bulunmaktadır. Bu sebeple kokusundan faydalanılabilir. Ruhsal açıdan rahatlama sağlarken, aynı zamanda içinde olunan ortamın temiz ve hoş kokmasına da katkıda bulunur. Özellikle, uykudan evvel yastığa ya da giyilen pijamaya birer damla damlatılabilir. Yoga ve meditasyon gibi aktiviteler sırasında konsantrasyonu yükseltir. Son olarak, tercihe göre başka kokularla da karıştırılıp ev ve oda parfümü olarak da yararlanılabilir.")
        yaglar.append(melisayagi)
        
        let menekseyagi = Yaglar(Adi: "Menekşe Yağı", Resim: UIImage(named: "menekseyagi")!, Faydalari: "Cilt hastalıkları egzama, dermatit ve uyuza karşı kullanılır,Mikrop öldürücüdür,Saç dökülmesine karşı etkilidir,Kuru saçları nemlendirir, parlaklık ve canlılık verir, cilde masaj yaparak veya saça friksiyon şeklinde kullanılır.Göz şişmesi ve mide şişkinliği için de menekşe yağı kullanılabilir. Menekşe yağını şişen gözünüzün üstüne masaj yaparak uygulayın.Mide şişkinliği için ise midenizin üzerine menekşe yağı ile masaj yapmalısınız.Menekşe yağı baş ağrısına iyi gelir.Cilt çatlaklarına karşı etkilidir.İdrar yaparken yanma sorununa,bitkisel bir çözümdür.Nezleye ve kalp sıkıntısına çok iyi gelir.Kanı temizleme özelliği vardır.Vücuda rahatlık verir.Antioksidandır.Nikris ve romatizmada faydalıdır.Kabızlığı giderir.Boğmaca ve boğaz ağrılarında faydalıdır.İdrar söktürücüdür.Sakinleştirici etkisi ile baş ağrısı, stres ve uykusuzluğa iyi gelir.Balgam söktürür.Egzama ve saç dökülmesinde oldukça etkilidir.", KullanimSekli: "Menekşe yağını saçlarınız için kullanacaksanız saçlarınıza direkt uygulamak yerine şampuanınıza birkaç damla ekleyebilirsiniz.Menekşe yağı ağız yoluyla tüketilmeyeceğinden, sıcak bir su içerisine birkaç damla ekleyerek solunum yolu ile bu yağdan faydalanabilirsiniz.Eğer hassas bir cilde sahipseniz ve cildiniz sık sık tahriş oluyorsa menekşe yağını kullanmadan önce mutlaka ufak bir bölümde test etmeli, herhangi bir reaksiyonda doktorunuza başvurmalısınız.Pek çok bitkisel yağ gibi menekşe yağının da piyasada birçok benzeri bulunmaktadır. Bu nedenle bitkisel yağları kullanmaya karar verdiğinizde bilindik ve tavsiye edilen markaları tercih etmeniz daha doğru olacaktır.Menekşe yağının en etkili kullanım şekillerinden birisi buhar yolu ile solumaktır. Bunun yanı sıra vücudunuz için de bakım yapmak istiyorsanız küvetteki suya birkaç damla ekleyerek hem kendinizi şımartabilir hem de rahatlatıcı bir bakım oluşturabilirsiniz.")
        yaglar.append(menekseyagi)
        
        let naneyagi = Yaglar(Adi: "Nane Yağı", Resim: UIImage(named: "naneyagi")!, Faydalari: "Doğal bir ağrı kesicidir. Özellikle karın ve kas ağrılarını giderir.Tıkalı sinüslerin açılmasına yardımcı olur.Kan dolaşımına olumlu etkileri vardır.Baş ağrılarına karşı etkilidir.Sindirimi kolaylaştırır, hazmı kolaylaştırır.Yüksek ateşi kısa sürede düşürür.İştah kapatıcı etkisi vardır.Mide bulantılarına karşı etkilidir.Grip, soğuk algınlığı ve nezle gibi hastalıkların olumsuz etkilerini azaltır.Konsantrasyonu arttırır, hafızayı güçlendirir.Alerji nedeniyle ortaya çıkan burun ve cilt kaşıntılarını azaltır.Saçta görülen kepek sorununa iyi gelir.Akne tedavisinde kullanılır.Antimikrobiyal özelliği vardır. Bu sayede bağışıklığı güçlendirir.Dudak çatlamalarını önler. Dudakların dolgunlaş görünmesine yardımcı olur.Ağız kokularını giderir. Ferahlatır.Vücuda enerji verir.", KullanimSekli: "Akne ve cildi nemlendirmek için; Doğrudan cilde sürülebilir. Ayrıca lavanta yağı gibi farklı yağlarla bir araya getirilerek de kullanılabilir.Güneş yanıkları için; 1 ölçek nane yağını, 1 ölçek hindistan cevizi yağı ile karıştırıp yanıkların olduğu bölgeye sürebilirsiniz.Kepek sorunu için; Kullandığınız şampuanın içerisine 1-2 damla nane yağı eklemek, kepek sorunundan kurtulmanıza yardımcı olacaktır.Hazımsızlık, bulantı ve ağız kokuları için; Bir bardak suyun içerisine 1-2 damla nane yağı damlatarak içebilirsiniz.Sinüs-burun tıkanıklığı, nefes darlığı için; Bir kasenin içerisine kaynar su dökün. Suyun içerisine 4-5 damla nane yağı ilave edin. Başınızın üzerine bir havlu örterek buhar banyosu yapın. Bu sayede tıkalı sinüsler açılır. Ayrıca horlama sorununa da iyi gelir.Baş ve kas ağrıları için; Nane yağını ağrıyan bölgeye sürüp masaj yapmanız yeterli olacaktır.")
        yaglar.append(naneyagi)
        
        let narcekirdegiyagi = Yaglar(Adi: "Nar Çekirdeği Yağı", Resim: UIImage(named: "narcekirdegiyagi")!, Faydalari: "Cilt dokusunun daha pırıltılı ve elastiki görünmesini sağlar.Nar çekirdeği yağı kırışıklıkların giderilmesine yardımcı olur.Ciltteki hücrelerin yenilenmesini sağlar.Cildin kaybettiği kolajeni ve cilde gerekli olan mineralleri kazandırır.Cildin yağ oranını dengeler ve cildi canlandırır.Nar çekirdeği yağının, yaşlanmayı önleyici ve tersine çevirici özellikleri de vardır.Saç derisindeki kan dolaşımını hızlandırıp kan damarlarını güçlendirir. Kepek ve kaşıntı gibi sorunları ciddi oranda azaltır.Cilt tonunu düzeltmeye yardımcı olur, renk eşitsizliklerini düzenler.Nar çekirdeği yağı selülit sorununa da çare olabilir. Hücre yenileyici özelliği sayesinde bu yağı masaj yaparak düzenli olarak kullandığınızda selülitlerinizin azaldığını görebilirsiniz.", KullanimSekli: "Bir pamuk yardımıyla bir iki damla cilt üzerine ve lekelere uygulanabilir. Hafif yağlardan olduğu için dilerseniz saç bakım maskelerinize de ekleyebilirsiniz.Nar çekirdeği yağı kırışıklık için de tercih edilen bitkisel yağlardandır. Yüz bölgesi hassas bir bölge olduğu için yağı su ile inceltip yüzünüze masaj yapabilirsiniz.Ağız yoluyla kullanmak isteyenler ise doktora danışıp eczanelerden veya aktarlardan nar çekirdeği yağı kapsülü alabilirler. Doktor tavsiyesi olmadan nar çekirdeği yağı kapsülü kullanmamanızı tavsiye edebiliriz.Nar çekirdeği yağı selülit için kullanılmak istendiğinde bir su ile karışım hazırlamanız gerekir. Bir fincan su içine 7 veya 8 damla yağ damlatın. Selülitli bölgeye bu karışım ile masaj yapın. Düzenli kullandığınız durumda, selülitlerin kaybolduğunu hissedeceksiniz.Güçlü antioksidan nardan elde edilen nar çekirdeği yağı, cilt ve saç sağlığınızı koruyarak sizi daha iyi hissettirir. Tüm vücut hücrelerinizi yenileyerek daha genç görünmenize katkıda bulunur. Ciltte ve saçta oluşan kaşınma gibi durumlarda en iyi bitkisel çözümdür.Nar çekirdeği yağı su ile inceltip göz altınızda morluk olan kısımlarda uygulamanız tavsiye edilebir. Göz ile direk temasından kaçınmalısınız. Uygulamadan sonra cildinizi yıkamayı unutmayın.")
        yaglar.append(narcekirdegiyagi)
        
        let okaliptus = Yaglar(Adi: "Okaliptus Yağı", Resim: UIImage(named: "okaliptusyagi")!, Faydalari: "Yağlı saçlarda kepek sorunu ve saç dökülmesini önler.Cilt lekelerini giderir.Akne ve sivilceleri önler.Siyah noktalarla savaşır.Cildin ihtiyacı olan besini sağlar.Yoğun tahribatı önler.Yara ve berelerin kısa sürede iyileşmesine yardımcı olur.Çeşitli cilt hastalıklarında kullanılır.Yanık tedavisinde de önerilir.Egzama ve mantarı giderir.", KullanimSekli: "Okaliptüs yağı; solunum yolu ile ve haricen kullanılabilmektedir. Solunum yolu ile kullanılması adına yastığa, birkaç damla kadar okaliptüs yağı damlatılmalıdır. Bunun dışında şişe ile kokusu çekilebilir. Okaliptüs yağı; sırta, göğse ya da boğaza da birkaç damla damlatılabilir. Bu şekilde masajı yaparak rahatlama sağlanabilecektir. Okaliptüs yağının cilde uygulanması için; okaliptüs yağı, bal ve limonlu bir karışım hazırlanarak vücuda sürülür. Bu karışım, cilt üzerinde 10 dakika boyunca bekletildikten sonra, duş alınmalıdır. Bu şekilde nemli ve yumuşak bir cilde sahip olunabilir.  ")
        yaglar.append(okaliptus)
        
        let papatyayagi = Yaglar(Adi: "Papatya Yağı", Resim: UIImage(named: "papatyayagi")!, Faydalari: "Papatya yağı cilde uygulandığında cilde parlaklık ve yumuşaklık verir. Papatya yağı cilde uygulanırken masaj yaparak uygulanmalıdır.Papatya yağı vücudu ve deriyi rahatlatıcı ve gevşetici etkiye sahiptir. Özellikle banyo öncesi masaj yapılması durumunda vücut çok rahatlar ve gevşer.Papatya yağının diğer bir faydası da ağrıyan eklem bölgelerine masaj yapılarak uygulandığında eklem ağrılarını azaltır.Eğer küçük bir bebeğiniz var ve karın ağrısı çekiyorsa bir kaç damla papatya yağı sürüp masaj yapın. Karın ağrısı çok kısa sürede gidecektir.Saç dökülmesi problemi yaşayanlara bire bir gelen papatya yağı, saçlara masaj yapılarak uygulandığında saç dökülmesini engeller ve saçları kuvvetlendirir.Saçlarında kepek sorunu yaşayanlara önerebileceğimiz papatya yağı kepek sorununa da çaredir.Saçları açmak içinde kullanılan papatya yağı aynı zamanda kuruyan saçları parlatır ve ışıl ışıl saç bırakır.Papatya yağı cilde sürüldüğünde yumuşacık ve kadifemsi bir cilt bırakır.", KullanimSekli:"Papatya yağının uygulanacağı yere göre kullanım şekli farklılık gösterebilmektedir. Bu kapsamda papatya yağı eğer ellere uygulanacaksa bunun için damlatılarak yayılması yeterli olacaktır.Eğer saça renk açmak amacıyla uygulanacaksa bu noktada dikkatli olunması önemlidir. Bu kapsamda papatya yağının saça uygulanmasından sonra bir kaç dakika bekletilmesi yeterli olacaktır. Saçta uzun süre kalması halinde renk açma etkisi artar.Papatya yağı yüz ve saçlar için hazırlanan maske ve kremlerin içine damlatılarak da kullanılabilir. Bu sayede hazırlanmış olan maske veya kremlerin olumlu yöndeki etkisinin çok daha fazla arttırılması sağlanabilir.Yeni doğan bebeklerin karın bölgesine iki damla damlatılarak masajla uygulandığında gaz probleminin hafiflemesine katkı sağlayıcı bir etki yaratır.Papatya yağı kullanımı hamilelerde ve çocuklarda kullanımı önerilmeyen bir üründür. Bu hususlara dikkat edilmesi oldukça önemli bir konudur.")
        yaglar.append(papatyayagi)
        
        let portakalyagi = Yaglar(Adi: "Portakal Yağı", Resim: UIImage(named: "portakalyagi")!, Faydalari: "Gerginlik ve stresi azaltır.Ağrıları dindirir.Bağırsakları çalıştırır.Vücudu toksinlerden arındırır.Cinsel duyguları canlandırır.Hücre onarımı sağlar.Saç dökülmesini önler.Selüliti giderir.Göğüs büyütücü etkisi vardır.Bitkisel antibiyotiktir.", KullanimSekli: "Portakal yağı 1 bardak içme suyuna 2 damla damlatılarak içilebilir.Cilt maskelerinin içerisine eklenerek kullanılabilir. Cilde direkt olarak temas ettirilmemesi önerilir. Yakıcı bir yağ olması nedeni ile göze temas ettirilmemesi gerekir.Saç bakımı için şampuanların içerisinde 2-3 damla damlatılarak kullanılabilir.Kas, eklem ve kemik ağrılarına banyo suyuna ekleyerek kullanılabilir.Kek kurabiye gibi yiyecekler yapılırken harçların içerisine eklenebilir. Bu hem güzel bir koku hem de güzel bir renk verir.Temizlik yaparken eve güzel bir koku vermesi amacıyla temizlik sularına katılabilir.")
        yaglar.append(portakalyagi)
        
        let rezeneyagi = Yaglar(Adi: "Rezene Yağı", Resim: UIImage(named: "rezeneyagi")!, Faydalari: "Bu yağ mide rahatsızlıklarında oldukça faydalıdır ve oluşmakta olan mide rahatsızlıklarını giderici etkiye sahiptir.Bağırsaklarda oluşan hastalıkların oluşumunu engeller.Rezene yağının iştah açıcı etkisi vardır.Doğum yapan bayanların çocukları emzirme döneminde sütü arttırıcı etkisi vardır.Bronşit rahatsızlığına ve oluşmakta olan öksürüğün söktürülmesine yardımcı olur.Kişilerde oluşmakta olan ağız kokularının giderilmesinde kullanılır.Rezene yağının cilde fayda sağlayıcı özelliği vardır. Cildin korunmasını ve temizlenmesini sağlar.Bu yağın banyoda duş duyuna katılarak kullanılmasında vücudun temizlenmesine yardımcı olur ve vücudu kötü kokulardan arındırır.Sindirim rahatsızlıklarında oldukça etkilidir ve sindirimi kolaylaştırır.Rezene yağının kullanımında balgam söktürücü etki vardır.Kanda oluşan iltihapları giderir.Kramp oluşan bölgelere masaj olarak uygulanmasında kramp gidericidir.Çocuklarda sıkça karşılaşılan karın ağrılarına iyi gelir.", KullanimSekli: "Rezene ve rezene yağı karakteristik özellikleri ile yüzyıllardır kullanılan ürünler olmuştur. Kokusu ile öne çıkan rezene yağı birçok amaç için kullanılabilmektedir. Rezene yağı uçucu yağlar sınıfında yer almaktadır. Sıcak banyo suyuna güzel koku yayması için birkaç damla eklenebilir. Rezene, kozmetik ve bakım sektöründe önemli bir yere sahiptir.Rezene yağı kişisel cilt bakım temizlik ürünlerine birkaç damla eklenebilir. Saç bakım ürünlerine de aynı şekilde eklenebilir.Cilt bakımının yanı sıra çayı da sıkça kullanılır. Rezene çayı bebeklere doktor tavsiyesi üzerine verilmelidir. Bu çayın bebeklerin gazını hafiflettiği halk arasında bilinmektedir.")
        yaglar.append(rezeneyagi)
        
        let sandalagaci = Yaglar(Adi: "Sandal Ağacı Yağı", Resim: UIImage(named: "sandalagaci")!, Faydalari: "Güneşin zararlı ışınlarının etkisi ve ilerleyen yaştan kaynaklı olarak cilt üzerinde oluşan lekelerin giderilmesinde etkilidir.Ciltte bulunan sivilce, siyah nokta, cilt kuruluğu gibi sorunların giderilmesinde fayda sağlar.Kuru ciltler için doğal bir nemlendiricidir.Düzenli olarak kullanılması durumunda ciltteki zararlı bakteri ve virüsleri temizler.Doğal bir balgam söktürücüdür.Sinüslerin açılmasını sağlayarak nefes almayı kolaylaştırır.Öksürük gibi sağlık sorunlarının tedavisinde etkilidir.Bel soğukluğu rahatsızlığının giderilmesinde etkilidir.Vücuttaki stres seviyesini azaltarak kaygı bozukluğu, depresyon, anksiyete gibi hastalıkların tedavisinde faydalıdır.Dizanteri hastalığının tedavisine yardımcı bir etki gösterir.Uykusuzluk sorunlarına iyi gelir.Sahip olduğu afrodizyak etki sayesinde cinsellik isteğinizin artmasına yardımcı olur.Kurumuş, çatlamış ve yıpranmış durumdaki ciltleri onarır.Ciltte biriken her türlü virüs ve bakterilerin arınmasına önemli ölçüde yardımcı olur.Ciltte şişlik ve kaşıntıya sebep olan böcek ısırığı gibi hassas şikayetlerin giderilmesi noktasında önemli bir etkiye sahiptir.Terleme problemini doğal yoldan çözer.Cilt yanıklarının azaltılmasını ve rahatlatılmasını sağlar.Cildin renk tonunu doğal olarak açan bir etki ortaya koyar.", KullanimSekli: "Sandal ağacı yağı harici olarak, cilt üzerine masaj ve friksiyon yapmak kaydıyla kullanılması önerilir. Hamileyseniz, bebek emziriyorsanız veya bir doktor bakımı altında tedavi görüyorsanız, kesinlikle doktorunuza danışın. Gözler, iç kulaklar ve hassas bölgelerle temas etmesinden kaçının.")
        yaglar.append(sandalagaci)
        
        let sarimsakyagi = Yaglar(Adi: "Sarımsak Yağı", Resim: UIImage(named: "sarimsakyagi")!, Faydalari: "Sarımsak yağı, antibakteriyel, antifungal ve antiviral özellikler gösteriyor.Ciltte oluşan sivilce, akne gibi sorunların önüne geçiyor.Mantar sorununa çözüm oluyor.Kolesterolü dengeliyor.Tansiyon sorununa iyi geliyor.Doğal bir ağrı kesici etkisi gösteriyor.Beynin sağlıkla çalışmasına destek oluyor.Diş ve diş eti sağlığını destekliyor.Sindirim sisteminin sağlıkla çalışmasına yardımcı oluyor.Bağırsak hareketlerini düzenliyor.Saç sorunlarını ortadan kaldırıyor.Kaşıntıya iyi geliyor.Saçların gürleşmesine ön ayak oluyor.Vücut direncini artırıyor.Birçok kanser türüne karşı da vücudu koruyucu bir etki gösteriyor.", KullanimSekli: "Sarımsak yağı hem yemeklere katılarak hem de harici olarak cilde ve saça sürülerek kullanılabiliyor. Ancak sarımsak yağı çok güçlü etkileri olan bir yağ olduğundan mutlaka zeytinyağı, badem yağı gibi farklı yağlarla karıştırmak gerekiyor.Sarımsak yağını yemeklerde kullanmak isterseniz herhangi bir yemeği yaparken zeytinyağı ya da tereyağının içine bir miktar karıştırabilirsiniz.Sarımsak yağını saçınıza ya da cildinize uygulayacaksanız, uygulayacağınız bölgenin büyüklüğüne göre bir miktar sarımsak yağını bir kaseye alıp üzerine aynı miktarda badem yağı, Hindistan cevizi yağı ya da zeytinyağı ekleyin ve güzelce karıştırın. Ardından dilerseniz cilt, dilerseniz saç sağlığınız için güvenle kullanabilirsiniz.")
        yaglar.append(sarimsakyagi)
        
        let sediragaci = Yaglar(Adi: "Sedir Ağacı Yağı", Resim: UIImage(named: "sediragaci")!, Faydalari: "Sedir ağacı yağı, cildi uyandırır ve canlandırmaya yardımcı olur. Artrit ağrılarını hafifletmeye yardımcı olur.Akne oluşumunu önler ve var olan aknelerin hızla iyileşmesini sağlar. Siyah nokta problemlerinin çözümünde oldukça etkilidir.Bronşite çok iyi gelir.Ciltte tahriş, kızarıklık, iltihaplanma, kaşıntı ile birlikte ciltte oluşan soyulmaya, çatlamaya ya da kabarmaya neden olan kuruluğu önemli ölçüde azaltmaya yardımcı olabilir.Saç dökülmesini önemli ölçüde azaltır.Doğal bir idrar söktürücüdür.Kaliteli bir uyku uyumanızı sağlar.Öksürüğü azaltır.Konsantrasyon eksikliğini azaltır.Sinir ve stresin azalmasına yardımcı olur.Kafa derisi ve egzama tedavisinde oldukça etkilidir.Sedir ağacı yağının antibakteriyel özelliği sayesinde mantar enfeksiyonlarının iyileştirilmesini sağlar.İnce telli saçların dökülmesini önler ve güçlenmesine yardımcı olur.Huzursuz bacak sendromu, astım, solunum nöbetleri ve spazmodik durumları hafifletmeye yardımcı olur.Dikkat dağınıklığına iyi gelir.Mide rahatsızlıklarına ve ağızda oluşan iltihaplanmalara iyi gelir.", KullanimSekli: "Sedir ağacı yağının fazla kullanılması cilde zarar verir ve cildi tahriş edebilir. Bu nedenle göz ve hassas bölgelere bu yağı temas ettirmemeye özen göstermeniz gerekir. Sedir ağacı yağı, cilde masaj yaparak uygulanır ve iyice cilde yedirilebilir. Bunun sedir ağacı yağının, ılık bir suyun içine birkaç damla damlatarak içilmesi önerilir. Bu yöntemi tercih etmek çok sağlıklı değildir. Yanlışlıkla fazla içildiği zaman mide bulantısı, kusma ve susuzluk gibi ciddi sorunlara neden olabilir. Aynı zamanda cilde pamuk yardımı ile sürülebilir.")
        yaglar.append(sediragaci)
        
        let sheayagi = Yaglar(Adi: "Shea (Karite) Yağı", Resim: UIImage(named: "sheayagi")!, Faydalari: "İyi bir nemlendirici kaynağıdır.A, E, F ve D vitaminleri bakımından zengin doğal bir antioksidandır.Yaşlanma etkilerini ve kırışıklıkları azaltır.Cildi pürüzsüz hale getirir.Ciltte kolajen üretimini artırır.Cilt lekelerini giderir.Derideki kaşıntı problemine iyi gelir.Egzama ve akne gibi sık görülen cilt rahatsızlıklarını önler.Topuk çatlaklarını giderir ve nasırları geçirir.Saç diplerini nemlendirir.Saçların sağlıklı uzamasına yardımcı olur.Kas yorgunluğuna iyi gelir.Eklem ağrılarının şiddetini hafifletir. ", KullanimSekli: "Kremsi kıvamı ile kullanımı ve uygulaması kolaydır. Normalde tereyağı gibi bir kıvamı olmasına karşın değişik ürünlerdeki kullanımı ile daha sıvı formlarda karşımıza çıkabilmektedir. Güzellik kremlerinde, sabunlarda ve saç bakım ürünlerinde kullanılabilmektedir. Tek başına kullanılabileceği gibi farklı yağlar ile karıştırılarak da kullanılabilir. Bu noktada önemli olan karışımın doğru şekilde ve oranlarda konunun uzmanları tarafından ya da onların gözetiminde yapılmasıdır.")
        yaglar.append(sheayagi)
        
        let soyayagi = Yaglar(Adi: "Soya Yağı", Resim: UIImage(named: "soyayagi")!, Faydalari: "Bitkisel yağ olduğundan dolayı kolesterol seviyesini yükseltmez. Kandaki kolesterol seviyesini azaltır.Omega 3 ve omega 6 vücudun alması gereken iki önemli yağ asididir. Soya yağı ile beraber bunlar da alınmış olur.Soya yağı birçok kanser türünün görülme sıklığını azaltır.Haricen kullanıldığı takdirde derinin ve tırnakların daha parlak bir görünüme kavuşmasını sağlar ve sağlıklı bir yapıda olmasını sağlar.Saç dökülmesine engel olurken saçların uzamasına da etki eder.Vücudun bağışıklık sistemini güçlendirir.İlerleyen yaşlarda görülebilen kemik erimesinde engelleyici etkisi olduğu ortaya çıkmıştır.Doymamış yağ konusunda çok sağlıklı ve etkili bir besin kaynağıdır.İçerisinde birçok vitaminin yanı sıra demir, magnezyum, çinko bulundurur.", KullanimSekli: "Bu sağlıklı yağ, yemeklik yağ gerektiren tüm tariflerde kullanılabilir.Salata sosu yapmak için sirke, tuz ve karabiber ile karıştırılabilir.Yüksek duman noktası sayesinde kızartma, fırınlama, kavurma veya sote gibi yüksek ısıda pişirme yöntemleri için diğer pişirme yağlarının yerine kullanılabilir.Soya yağı yemeklerde kullanımının yanı sıra, doğal bir nemlendirici olduğu için saça ve cilde de uygulanabilir.")
        yaglar.append(soyayagi)
        
        let susamyagi = Yaglar(Adi: "Susam Yağı", Resim: UIImage(named: "susamyagi")!, Faydalari: "Antioksidan vitamin ve mineral içeriğine sahip olan susam yağı vücudun bağışıklık sistemini güçlendirerek hastalıklara karşı koruyucu etki gösterir.Bünyesinde bulunan demirden dolayı kansızlığın tedavisini destekleyen bitkisel yağ kolesterolün dengelenmesine iyi gelir.Ciltte oluşan yanık ve yaraların tedavisinde kullanılan susam yağı içeriğindeki E vitamininden dolayı hücre yenilenmesine yardımcı olur.Güneşin zararlı ışınlarına karşı koruyucu etkisi olan susam yağı güneş koruyucu olarak da kullanılır.Antibakteriyel etkiye sahip olan susam yağı ağrı kesici olarak oldukça etkilidir.Dişleri fırçalamadan önce dişlere sürülen susam yağı diş beyazlatma için kullanılır.Ağız içine alınan 1 yemek kaşığı susam yağı yaklaşık 10 dakika ağızda bekletildikten sonra dişler ılık su ile fırçalanır.Kan şekerinin düzenlenmesine yardımcıdır ve bu özelliğinden dolayı susam yağı şeker hastalığı tedavisinde de etkin rol oynar.Çinko açısından zengin olan susam yağı sivilce oluşumunu engeller ve cildin pürüzsüz görünmesini sağlar.Susam yağı Ender Saraç tarafından da ele alınmıştır. Diz ağrıları için susam yağı kullanımı öneren Saraç, düzenli kullanıldığında diz ağrılarına iyi geldiğini söylemektedir.Solunumu rahatlatması susam yağı faydaları arasında bilinen bir diğer özelliğidir.Baş ağrılarınız ve özellikle migren atakları için susam yağı ile masaj yapabilirsiniz; ağrıyı dindirecektir.Duygu durum bozuklukları, aniden agresifleşme gibi sinirsel problemleri yatıştırır.Susam yağı uyku düzensizliği için kullanılabilir.", KullanimSekli: "Dilerseniz susam yağını aynı miktarda zeytinyağıyla bir araya getirerek salata sosu olarak kullanabilirsiniz.Susam yağını cildinizde ve saçınızda kullanmak isterseniz yine kullanacağınız susam yağı kadar zeytinyağı ya da badem yağı ile karıştırarak kullanabilir. Cildinize ya da saç derinize parmak uçlarınızla masaj yaparak uygulayabilirsiniz.Saçınıza sürdüğünüzde en az 2-3 saat boyunca bekletip ardından yıkamanız yeterli olacaktır. Cildinize sürdüğünüzdeyse isterseniz nemlendirmek amaçlı sürebilir isterseniz de duşa girmeden önce sürüp bir süre beklettikten sonra durulayabilirsiniz.")
        yaglar.append(susamyagi)
        
        let tarcinyagi = Yaglar(Adi: "Tarçın Yağı", Resim: UIImage(named: "tarcinyagi")!, Faydalari: "Tarçın yağı antibakteriyel etkiye sahiptir. Mikrop öldürücü özelliği en önemli özelliğidir.Kan şekerini düşürür.Romatizmal ağrılara faydalıdır.Bağırsakları düzenler.Bağırsak solucanları için faydalı olur.Hazmı kolaylaştırır.Ağrıları dindirir.Mide kramplarını giderir.Cinsel gücü artırır.Ruhi sıkıntılar için çok yararlıdır.Kalbi kuvvetlendirir.Grip, soğuk algınlığı ve nezleye iyi gelir.iştahsızlık için kullanılır.Mide tembelliğine faydalıdır.Vücut direncini artırır.Kadınlardaki beyaz akıntıya karşı başarıyla kullanılır.Haricen kaşıntı ve haşere sokmalarına karşı kullanılır.Kan dolaşımını hızlandırır.", KullanimSekli: "Tarçın yağı suya damlatılarak içilebilir. Ayrıca tarçın yağı vücuda sürülerek de yaraları iyileştirebilir. Banyo sularına tarçın yağı damlatılması da stresi ve günün yorgunluğunu alabilir. Cilt sorunlarını gidermek için de tarçın yağı yüze sürülebilir.")
        yaglar.append(tarcinyagi)
        
        let vanilyayagi = Yaglar(Adi: "Vanilya Yağı", Resim: UIImage(named: "vanilyayagi")!, Faydalari: "Depresyon ve anksiyete belirtilerini azaltırAntioksidan bakımından zengin olan vanilya, serbest radikallerin neden olduğu cilt hasarını önler. İnce çizgiler, kırışıklıklar ve yaşlılık lekeleri gibi yaşlanma belirtilerini yavaşlatmaya yardımcı olur.Libidoyu artırır. Vanilya yağında ateşe neden olabilecek enfeksiyonlarla savaşan bileşenler vardır. Ateşin neden olduğu iltihabı azaltır.Adet semptomlarını azaltır.Kanser hücrelerinin büyümesini önler.Vücutta meydana gelen enfeksiyonlarla savaşır.Sakinleştiricidir.Uyku kalitesini artırır.Solunumu destekler.Kan basıncını düşürür.Vanilya yağında bulunan niasin, tiamin ve pantotenik asit, cilt sağlığını geliştirmeye, cildi sivilcelerden uzak tutmaya yardımcı olur.Saç köklerini güçlendirir.Diş ağrısını hafifletir.", KullanimSekli: "Kas ağrıları, kramplar için ağrıyan bölgelere küçük ovar hareketlerle masaj yapabilirsiniz.Vücudunuzu,  zihninizi rahatlatmak için boynunuza, ayaklarınıza, göğsünüze ve karnınıza vanilya yağını nazik ovar hareketlerle uygulayabilirsiniz. Masajla ovma hareketleri kas ağrılarınızı, PMS kramplarınızı, anksiyete ve diğer stres sorunlarınızı hafifletirek cildiniz için antibakteriyel bir etkiyle de yardımcı olur.Uyku düzenini iyileştirmekte vanilya yağı benim ne işime yarayacak diyorsanız, sabah uyandığınızda gülümsetecek güzel bir öneri: yatmadan önce 3–5 damla vanilya yağı içinize çekerek rahatlıkla mis gibi bir uykuya geçin ve sabah mis gibi uyanın.Vanilya yağını cilt sağlığı için kullanmak için, günlük yüz yıkama veya losyonunuza 2–3 damla ekleyin. Ev Yapımı Yüz Yıkama ürünüme 5 damla saf vanilya yağı veya vanilya yağı infüzyonu eklemeyi deneyin")
        yaglar.append(vanilyayagi)
        
        let yaseminyagi = Yaglar(Adi: "Yasemin Yağı", Resim: UIImage(named: "yaseminyagi")!, Faydalari: "Enerjiyi arttırır.Bağışıklık sistemini güçlendirir.Yağ yakmak için kullanılır.Konsantrasyonu arttırır.Stresi azaltır.Kalp hastalıklarından korunmak için kullanılır.Kolesterolü düşürmeye yardımcı olur.Kas ağrılarını hafifletir.Soğuk algınlığına iyi gelir.Şeker hastalığının tedavisine yardımcı olur.Alerji belirtilerini hafifletir.Eklem ağrılarını azaltır.Bel ve sırt ağrısına karşı kullanılır.Antioksidandır.Depresyon belirtilerini azaltır.Kan basıncını düşürür.Saçtaki hasarı kontrol altına alır. Kurutma makinesi ya da şekillendiricilerin verdiği yıpratmadan saçı korur ve hasar görmüş saçı onarır.Saç köklerini güçlendirir. Saç derisi için de çok besleyicidir. Kuru ve kırılgan saçların onarımında da oldukça etkilidir.Saçın doğal rengini korur. Ayrıca kınayla boyanmış saçlar için doğal bir saç kremidir; yumuşak ve ipeksi görünenen saçlara kavuşmanızı sağlar.Kuru ve kıvırcık saçlar için uygundur. Tüm saç tipleri için kullanılabilir, ancak kuru ve kontrol edilmeyen kıvırcık saçlar için idealdir. Saçı parlatır ve nemlendirir.Antiseptik özelliği ile saç derisinden mikropları temizler.Bitler ve yumurtaları için tedavi edicidir. Diğer baz yağlarla (zeytinyağı, badem yağı vb) beraber kullanıldığında, yasemin yağı bit ve sirke üremesini engeller.Zihni sakinleştirir. Birkaç damla yasemin yağının saçta ve zihinde rahatlatıcı etkisi vardır. Aroması zihni yatıştırır ve stresi azaltır.", KullanimSekli: "Yasemin yağı direkt olarak cilde uygulanabilir veya tıkanık ve öksürüklerin önüne geçmek için direkt olarak teneffüs de edilebilir.Gündelik olarak cildin yenilenmesi için kullanılan el losyonlarına birkaç damla damlatılarak kullanılabilir. Kas ağrıları çeken kişiler süt içerisine birkaç damla ekleyerek ağrı bölgelerine sürebilir. Solunum yolları ile burnu temizlemek için sıcak su içerisine birkaç damla damlatılarak solunabilir.Yasemin yağı, kuru saç derisine direkt olarak uygulandığı zaman saçı ve saç derisini nemlendirmektedir. 1 tatlı kaşığı yasemin yağı ile 3 tatlı kaşığı zeytinyağı, badem yağı ve üzüm çekirdeği yağı karıştırılır. Yıkanmış olan saça ıslak parmaklarla uygulanır.")
        yaglar.append(yaseminyagi)
        
        let ylangylang = Yaglar(Adi: "Ylang Ylang Yağı", Resim: UIImage(named: "ylangyagi")!, Faydalari: "Kardiyovasküler sistemdeki iltihaplanmayı engelleyici özelliğe sahiptir.Kullanıcısına hem zihnen hem de bedenen rahatlama hissi sunar,stres oranını azaltır.Sindirim sisteminde bulunan bakteri ve enfeksiyonların giderilmesinde etkilidir.Antibakteriyel özellikleri sayesinde vücudunuzda bulunan yaraların giderilmesinde etkilidir.Mantar hastalığının tedavisinde etkilidir.Panik, stres, uykusuzluk, endişe ve şok gibi durumlarda etkilidir.Güçlü bir afrodizyak etkiye sahip olan ylang ylang yağı, enerji verici bir özelliğe sahiptir.Ciltteki sebum oranını dengeleyerek sivilce ve siyah nokta oluşumunu engeller.İçerisinde birçok vitamin ve mineral bulunduğundan saç sağlığı için de oldukça yararlıdır,kepeği önler.Sindirim sisteminin çalışmasına destek olur, kilo vermek amacıyla da tercih edilebilir.Egzama, akne, sedef gibi çeşitli cilt rahatsızlıklarının tedavi edilmesinde etkilidir.Ylang ylang yağı, regl döneminde kadınların yoğun olarak yaşadığı karın ağrısı, kasılma gibi semptomları en aza indirmektedir.", KullanimSekli: "Masaj uygulamasında kullandığınız yağların içerisine 4-5 damla ylang ylang yağı ekleyerek masaj yağının rahatlatıcı etkisini kolayca arttırabilirsiniz. Bu yağı saç bakımınızda ve cilt bakımınızda kullanmanız uygundur.Saç maskelerinize birkaç damla katarak saçınızda 15-20 dakika bekletmeniz yeterlidir. Sonrasında ılık su ile yıkayabilirsiniz.")
        yaglar.append(ylangylang)
        
        let zeytinyagi = Yaglar(Adi: "Zeytin Yağı", Resim: UIImage(named: "zeytinyagi")!, Faydalari: "Karaciğeri temizler.Sindirimi düzenler.Metabolizmayı hızlandırır.Kemikleri güçlendirir.Cildi korur.Kan basıncını düzenler.Stresi azaltır.Kan şeker seviyesini düşürür.Saç bakımındada faydalıdır. ", KullanimSekli: "Zeytinyağını kullanabileceğiniz alanlar sınırsızdır. Mutfakta; salataya ve yemeklere ekleyebilir, ayrıca kızartma yapabilirsiniz. Kahvaltıda bir tabağa koyup, biraz baharat da ekleyerek ekmeğinizi banabilirsiniz. Bunun dışında cildiniz için de son derece faydalı ve besleyicidir. Aç karna bir çorba kaşığı içerek kabızlığı önleyebilirsiniz.")
        yaglar.append(zeytinyagi)
    }
}
